//###################################################################
//
// DON'T EDIT!
//
// This file is auto generated by
//    >php -f PinConfig.php PinConfig_STM32F769.csv
//
//###################################################################

//*******************************************************************
#include "Mcu_Types.h"
#include "Std/Report.h"

//*******************************************************************
namespace EmbSysLib {
namespace Hw {

//*******************************************************************
/*!
\class PinConfig

\brief Port pin configuration

This class provides methods to
- configure GPIO mode, type, pull-up/-down, speed and alternate
  function
- connect a GPIO to an alternate function
*/
class PinConfig
{
  public:
    //---------------------------------------------------------------
    /*! \enum MODE
        \brief Pin mode configuration
    */
    typedef enum
    {
      // MODER
      INPUT          = 0x0000, //!< Input mode
      OUTPUT         = 0x0001, //!< Output mode
      ALTERNATE_FUNC = 0x0002, //!< Alternate function
      ANALOG         = 0x0003, //!< Analog I/O

      // OTYPER
      PUSH_PULL      = 0x0000, //!< Enable push-pull
      OPEN_DRAIN     = 0x0010, //!< Disable push-pull

      //PUPDR
      NO_PUPD        = 0x0000, //!< No pull-up or pull down
      PULL_UP        = 0x0100, //!< Enable pull-up
      PULL_DOWN      = 0x0200, //!< Enable pull-down

      //OSPEEDR
      LOW_SPEED      = 0x0000, //!< Low speed mode
      MEDIUM_SPEED   = 0x1000, //!< Medium speed mode
      FAST_SPEED     = 0x2000, //!< Fast speed mode
      HIGH_SPEED     = 0x3000  //!< High speed mode

    } MODE;

    //---------------------------------------------------------------
    /*! Alternate functions of the MCU
    */
    typedef enum
    { 
      ADC1_IN0,
      ADC1_IN1,
      ADC1_IN10,
      ADC1_IN11,
      ADC1_IN12,
      ADC1_IN13,
      ADC1_IN14,
      ADC1_IN15,
      ADC1_IN2,
      ADC1_IN3,
      ADC1_IN4,
      ADC1_IN5,
      ADC1_IN6,
      ADC1_IN7,
      ADC1_IN8,
      ADC1_IN9,
      ADC2_IN0,
      ADC2_IN1,
      ADC2_IN10,
      ADC2_IN11,
      ADC2_IN12,
      ADC2_IN13,
      ADC2_IN14,
      ADC2_IN15,
      ADC2_IN2,
      ADC2_IN3,
      ADC2_IN4,
      ADC2_IN5,
      ADC2_IN6,
      ADC2_IN7,
      ADC2_IN8,
      ADC2_IN9,
      ADC3_IN0,
      ADC3_IN1,
      ADC3_IN10,
      ADC3_IN11,
      ADC3_IN12,
      ADC3_IN13,
      ADC3_IN14,
      ADC3_IN15,
      ADC3_IN2,
      ADC3_IN3,
      ADC3_IN4,
      ADC3_IN5,
      ADC3_IN6,
      ADC3_IN7,
      ADC3_IN8,
      ADC3_IN9,
      CAN1_RX,
      CAN1_TX,
      CAN2_RX,
      CAN2_TX,
      CAN3_RX,
      CAN3_TX,
      CEC1,
      DAC_OUT1,
      DAC_OUT2,
      DCMI_D0,
      DCMI_D1,
      DCMI_D10,
      DCMI_D11,
      DCMI_D12,
      DCMI_D13,
      DCMI_D2,
      DCMI_D3,
      DCMI_D4,
      DCMI_D5,
      DCMI_D6,
      DCMI_D7,
      DCMI_D8,
      DCMI_D9,
      DCMI_HSYNC,
      DCMI_PIXCLK,
      DCMI_VSYNC,
      DFSDM1_CKIN0,
      DFSDM1_CKIN1,
      DFSDM1_CKIN2,
      DFSDM1_CKIN3,
      DFSDM1_CKIN4,
      DFSDM1_CKIN5,
      DFSDM1_CKIN6,
      DFSDM1_CKIN7,
      DFSDM1_CKOUT,
      DFSDM1_DATIN0,
      DFSDM1_DATIN1,
      DFSDM1_DATIN2,
      DFSDM1_DATIN3,
      DFSDM1_DATIN4,
      DFSDM1_DATIN5,
      DFSDM1_DATIN6,
      DFSDM1_DATIN7,
      DSIHOST_TE,
      ETH_COL,
      ETH_CRS,
      ETH_CRS_DV,
      ETH_MDC,
      ETH_MDIO,
      ETH_PPS_OUT,
      ETH_REF_CLK,
      ETH_RXD0,
      ETH_RXD1,
      ETH_RXD2,
      ETH_RXD3,
      ETH_RX_CLK,
      ETH_RX_DV,
      ETH_RX_ER,
      ETH_TXD0,
      ETH_TXD1,
      ETH_TXD2,
      ETH_TXD3,
      ETH_TX_CLK,
      ETH_TX_EN,
      FMC_A0,
      FMC_A1,
      FMC_A10,
      FMC_A11,
      FMC_A12,
      FMC_A13,
      FMC_A14,
      FMC_A15,
      FMC_A16,
      FMC_A17,
      FMC_A18,
      FMC_A19,
      FMC_A2,
      FMC_A20,
      FMC_A21,
      FMC_A22,
      FMC_A23,
      FMC_A24,
      FMC_A25,
      FMC_A3,
      FMC_A4,
      FMC_A5,
      FMC_A6,
      FMC_A7,
      FMC_A8,
      FMC_A9,
      FMC_ALE,
      FMC_BA0,
      FMC_BA1,
      FMC_CLE,
      FMC_CLK,
      FMC_D0,
      FMC_D1,
      FMC_D10,
      FMC_D11,
      FMC_D12,
      FMC_D13,
      FMC_D14,
      FMC_D15,
      FMC_D16,
      FMC_D17,
      FMC_D18,
      FMC_D19,
      FMC_D2,
      FMC_D20,
      FMC_D21,
      FMC_D22,
      FMC_D23,
      FMC_D24,
      FMC_D25,
      FMC_D26,
      FMC_D27,
      FMC_D28,
      FMC_D29,
      FMC_D3,
      FMC_D30,
      FMC_D31,
      FMC_D4,
      FMC_D5,
      FMC_D6,
      FMC_D7,
      FMC_D8,
      FMC_D9,
      FMC_DA0,
      FMC_DA1,
      FMC_DA10,
      FMC_DA11,
      FMC_DA12,
      FMC_DA13,
      FMC_DA14,
      FMC_DA15,
      FMC_DA2,
      FMC_DA3,
      FMC_DA4,
      FMC_DA5,
      FMC_DA6,
      FMC_DA7,
      FMC_DA8,
      FMC_DA9,
      FMC_INT,
      FMC_NBL0,
      FMC_NBL1,
      FMC_NBL2,
      FMC_NBL3,
      FMC_NCE,
      FMC_NE1,
      FMC_NE2,
      FMC_NE3,
      FMC_NE4,
      FMC_NL,
      FMC_NOE,
      FMC_NWAIT,
      FMC_NWE,
      FMC_SDCKE0,
      FMC_SDCKE1,
      FMC_SDCLK,
      FMC_SDNCAS,
      FMC_SDNE0,
      FMC_SDNE1,
      FMC_SDNRAS,
      FMC_SDNWE,
      I2C1_SCL,
      I2C1_SDA,
      I2C1_SMBA,
      I2C2_SCL,
      I2C2_SDA,
      I2C2_SMBA,
      I2C3_SCL,
      I2C3_SDA,
      I2C3_SMBA,
      I2C4_SCL,
      I2C4_SDA,
      I2C4_SMBA,
      I2S1_CK,
      I2S1_MCK,
      I2S1_SD,
      I2S1_WS,
      I2S2_CK,
      I2S2_MCK,
      I2S2_SD,
      I2S2_WS,
      I2S3_CK,
      I2S3_MCK,
      I2S3_SD,
      I2S3_WS,
      I2S_CKIN,
      LPTIM1_ETR,
      LPTIM1_IN1,
      LPTIM1_IN2,
      LPTIM1_OUT,
      LTDC_B0,
      LTDC_B1,
      LTDC_B2,
      LTDC_B3,
      LTDC_B4,
      LTDC_B5,
      LTDC_B6,
      LTDC_B7,
      LTDC_CLK,
      LTDC_DE,
      LTDC_G0,
      LTDC_G1,
      LTDC_G2,
      LTDC_G3,
      LTDC_G4,
      LTDC_G5,
      LTDC_G6,
      LTDC_G7,
      LTDC_HSYNC,
      LTDC_R0,
      LTDC_R1,
      LTDC_R2,
      LTDC_R3,
      LTDC_R4,
      LTDC_R5,
      LTDC_R6,
      LTDC_R7,
      LTDC_VSYNC,
      MDIOS_MDC,
      MDIOS_MDIO,
      QUADSPI_BK1_IO0,
      QUADSPI_BK1_IO1,
      QUADSPI_BK1_IO2,
      QUADSPI_BK1_IO3,
      QUADSPI_BK1_NCS,
      QUADSPI_BK2_IO0,
      QUADSPI_BK2_IO1,
      QUADSPI_BK2_IO2,
      QUADSPI_BK2_IO3,
      QUADSPI_BK2_NCS,
      QUADSPI_CLK,
      RCC_MCO_1,
      RCC_MCO_2,
      RTC_REFIN,
      SAI1_FS_A,
      SAI1_FS_B,
      SAI1_MCLK_A,
      SAI1_MCLK_B,
      SAI1_SCK_A,
      SAI1_SCK_B,
      SAI1_SD_A,
      SAI1_SD_B,
      SAI2_FS_A,
      SAI2_FS_B,
      SAI2_MCLK_A,
      SAI2_MCLK_B,
      SAI2_SCK_A,
      SAI2_SCK_B,
      SAI2_SD_A,
      SAI2_SD_B,
      SDMMC1_CK,
      SDMMC1_CMD,
      SDMMC1_D0,
      SDMMC1_D1,
      SDMMC1_D2,
      SDMMC1_D3,
      SDMMC1_D4,
      SDMMC1_D5,
      SDMMC1_D6,
      SDMMC1_D7,
      SDMMC2_CK,
      SDMMC2_CMD,
      SDMMC2_D0,
      SDMMC2_D1,
      SDMMC2_D2,
      SDMMC2_D3,
      SDMMC2_D4,
      SDMMC2_D5,
      SDMMC2_D6,
      SDMMC2_D7,
      SPDIFRX_IN0,
      SPDIFRX_IN1,
      SPDIFRX_IN2,
      SPDIFRX_IN3,
      SPI1_MISO,
      SPI1_MOSI,
      SPI1_NSS,
      SPI1_SCK,
      SPI2_MISO,
      SPI2_MOSI,
      SPI2_NSS,
      SPI2_SCK,
      SPI3_MISO,
      SPI3_MOSI,
      SPI3_NSS,
      SPI3_SCK,
      SPI4_MISO,
      SPI4_MOSI,
      SPI4_NSS,
      SPI4_SCK,
      SPI5_MISO,
      SPI5_MOSI,
      SPI5_NSS,
      SPI5_SCK,
      SPI6_MISO,
      SPI6_MOSI,
      SPI6_NSS,
      SPI6_SCK,
      SYS_JTCK_SWCLK,
      SYS_JTDI,
      SYS_JTDO_SWO,
      SYS_JTMS_SWDIO,
      SYS_JTRST,
      SYS_TRACECLK,
      SYS_TRACED0,
      SYS_TRACED1,
      SYS_TRACED2,
      SYS_TRACED3,
      TIM10_CH1,
      TIM11_CH1,
      TIM12_CH1,
      TIM12_CH2,
      TIM13_CH1,
      TIM14_CH1,
      TIM1_BKIN,
      TIM1_BKIN2,
      TIM1_CH1,
      TIM1_CH1N,
      TIM1_CH2,
      TIM1_CH2N,
      TIM1_CH3,
      TIM1_CH3N,
      TIM1_CH4,
      TIM1_ETR,
      TIM2_CH1,
      TIM2_CH2,
      TIM2_CH3,
      TIM2_CH4,
      TIM2_ETR,
      TIM3_CH1,
      TIM3_CH2,
      TIM3_CH3,
      TIM3_CH4,
      TIM3_ETR,
      TIM4_CH1,
      TIM4_CH2,
      TIM4_CH3,
      TIM4_CH4,
      TIM4_ETR,
      TIM5_CH1,
      TIM5_CH2,
      TIM5_CH3,
      TIM5_CH4,
      TIM8_BKIN,
      TIM8_BKIN2,
      TIM8_CH1,
      TIM8_CH1N,
      TIM8_CH2,
      TIM8_CH2N,
      TIM8_CH3,
      TIM8_CH3N,
      TIM8_CH4,
      TIM8_ETR,
      TIM9_CH1,
      TIM9_CH2,
      UART4_CTS,
      UART4_DE,
      UART4_RTS,
      UART4_RX,
      UART4_TX,
      UART5_CTS,
      UART5_DE,
      UART5_RTS,
      UART5_RX,
      UART5_TX,
      UART7_CTS,
      UART7_DE,
      UART7_RTS,
      UART7_RX,
      UART7_TX,
      UART8_CTS,
      UART8_DE,
      UART8_RTS,
      UART8_RX,
      UART8_TX,
      USART1_CK,
      USART1_CTS,
      USART1_DE,
      USART1_RTS,
      USART1_RX,
      USART1_TX,
      USART2_CK,
      USART2_CTS,
      USART2_DE,
      USART2_RTS,
      USART2_RX,
      USART2_TX,
      USART3_CK,
      USART3_CTS,
      USART3_DE,
      USART3_RTS,
      USART3_RX,
      USART3_TX,
      USART6_CK,
      USART6_CTS,
      USART6_DE,
      USART6_RTS,
      USART6_RX,
      USART6_TX,
      USB_OTG_FS_DM,
      USB_OTG_FS_DP,
      USB_OTG_FS_ID,
      USB_OTG_FS_SOF,
      USB_OTG_HS_DM,
      USB_OTG_HS_DP,
      USB_OTG_HS_ID,
      USB_OTG_HS_SOF,
      USB_OTG_HS_ULPI_CK,
      USB_OTG_HS_ULPI_D0,
      USB_OTG_HS_ULPI_D1,
      USB_OTG_HS_ULPI_D2,
      USB_OTG_HS_ULPI_D3,
      USB_OTG_HS_ULPI_D4,
      USB_OTG_HS_ULPI_D5,
      USB_OTG_HS_ULPI_D6,
      USB_OTG_HS_ULPI_D7,
      USB_OTG_HS_ULPI_DIR,
      USB_OTG_HS_ULPI_NXT,
      USB_OTG_HS_ULPI_STP,
    } Function;

    //---------------------------------------------------------------
    /*! Pin function mapping

        Maps an alternate function to a port pin and alternate function ID.
       'ADC12_IN4_PA4' means: The function 'ADC12_IN4' is mapped to pin PA4
    */
    typedef enum
    { 
      ADC1_IN0_PA0         = (ADC1_IN0            <<16)|( 0<<12)|( 0<<4)|( 0<<0), //!<\n
      ADC1_IN1_PA1         = (ADC1_IN1            <<16)|( 0<<12)|( 1<<4)|( 0<<0), //!<\n
      ADC1_IN10_PC0        = (ADC1_IN10           <<16)|( 2<<12)|( 0<<4)|( 0<<0), //!<\n
      ADC1_IN11_PC1        = (ADC1_IN11           <<16)|( 2<<12)|( 1<<4)|( 0<<0), //!<\n
      ADC1_IN12_PC2        = (ADC1_IN12           <<16)|( 2<<12)|( 2<<4)|( 0<<0), //!<\n
      ADC1_IN13_PC3        = (ADC1_IN13           <<16)|( 2<<12)|( 3<<4)|( 0<<0), //!<\n
      ADC1_IN14_PC4        = (ADC1_IN14           <<16)|( 2<<12)|( 4<<4)|( 0<<0), //!<\n
      ADC1_IN15_PC5        = (ADC1_IN15           <<16)|( 2<<12)|( 5<<4)|( 0<<0), //!<\n
      ADC1_IN2_PA2         = (ADC1_IN2            <<16)|( 0<<12)|( 2<<4)|( 0<<0), //!<\n
      ADC1_IN3_PA3         = (ADC1_IN3            <<16)|( 0<<12)|( 3<<4)|( 0<<0), //!<\n
      ADC1_IN4_PA4         = (ADC1_IN4            <<16)|( 0<<12)|( 4<<4)|( 0<<0), //!<\n
      ADC1_IN5_PA5         = (ADC1_IN5            <<16)|( 0<<12)|( 5<<4)|( 0<<0), //!<\n
      ADC1_IN6_PA6         = (ADC1_IN6            <<16)|( 0<<12)|( 6<<4)|( 0<<0), //!<\n
      ADC1_IN7_PA7         = (ADC1_IN7            <<16)|( 0<<12)|( 7<<4)|( 0<<0), //!<\n
      ADC1_IN8_PB0         = (ADC1_IN8            <<16)|( 1<<12)|( 0<<4)|( 0<<0), //!<\n
      ADC1_IN9_PB1         = (ADC1_IN9            <<16)|( 1<<12)|( 1<<4)|( 0<<0), //!<\n
      ADC2_IN0_PA0         = (ADC2_IN0            <<16)|( 0<<12)|( 0<<4)|( 0<<0), //!<\n
      ADC2_IN1_PA1         = (ADC2_IN1            <<16)|( 0<<12)|( 1<<4)|( 0<<0), //!<\n
      ADC2_IN10_PC0        = (ADC2_IN10           <<16)|( 2<<12)|( 0<<4)|( 0<<0), //!<\n
      ADC2_IN11_PC1        = (ADC2_IN11           <<16)|( 2<<12)|( 1<<4)|( 0<<0), //!<\n
      ADC2_IN12_PC2        = (ADC2_IN12           <<16)|( 2<<12)|( 2<<4)|( 0<<0), //!<\n
      ADC2_IN13_PC3        = (ADC2_IN13           <<16)|( 2<<12)|( 3<<4)|( 0<<0), //!<\n
      ADC2_IN14_PC4        = (ADC2_IN14           <<16)|( 2<<12)|( 4<<4)|( 0<<0), //!<\n
      ADC2_IN15_PC5        = (ADC2_IN15           <<16)|( 2<<12)|( 5<<4)|( 0<<0), //!<\n
      ADC2_IN2_PA2         = (ADC2_IN2            <<16)|( 0<<12)|( 2<<4)|( 0<<0), //!<\n
      ADC2_IN3_PA3         = (ADC2_IN3            <<16)|( 0<<12)|( 3<<4)|( 0<<0), //!<\n
      ADC2_IN4_PA4         = (ADC2_IN4            <<16)|( 0<<12)|( 4<<4)|( 0<<0), //!<\n
      ADC2_IN5_PA5         = (ADC2_IN5            <<16)|( 0<<12)|( 5<<4)|( 0<<0), //!<\n
      ADC2_IN6_PA6         = (ADC2_IN6            <<16)|( 0<<12)|( 6<<4)|( 0<<0), //!<\n
      ADC2_IN7_PA7         = (ADC2_IN7            <<16)|( 0<<12)|( 7<<4)|( 0<<0), //!<\n
      ADC2_IN8_PB0         = (ADC2_IN8            <<16)|( 1<<12)|( 0<<4)|( 0<<0), //!<\n
      ADC2_IN9_PB1         = (ADC2_IN9            <<16)|( 1<<12)|( 1<<4)|( 0<<0), //!<\n
      ADC3_IN0_PA0         = (ADC3_IN0            <<16)|( 0<<12)|( 0<<4)|( 0<<0), //!<\n
      ADC3_IN1_PA1         = (ADC3_IN1            <<16)|( 0<<12)|( 1<<4)|( 0<<0), //!<\n
      ADC3_IN10_PC0        = (ADC3_IN10           <<16)|( 2<<12)|( 0<<4)|( 0<<0), //!<\n
      ADC3_IN11_PC1        = (ADC3_IN11           <<16)|( 2<<12)|( 1<<4)|( 0<<0), //!<\n
      ADC3_IN12_PC2        = (ADC3_IN12           <<16)|( 2<<12)|( 2<<4)|( 0<<0), //!<\n
      ADC3_IN13_PC3        = (ADC3_IN13           <<16)|( 2<<12)|( 3<<4)|( 0<<0), //!<\n
      ADC3_IN14_PF4        = (ADC3_IN14           <<16)|( 5<<12)|( 4<<4)|( 0<<0), //!<\n
      ADC3_IN15_PF5        = (ADC3_IN15           <<16)|( 5<<12)|( 5<<4)|( 0<<0), //!<\n
      ADC3_IN2_PA2         = (ADC3_IN2            <<16)|( 0<<12)|( 2<<4)|( 0<<0), //!<\n
      ADC3_IN3_PA3         = (ADC3_IN3            <<16)|( 0<<12)|( 3<<4)|( 0<<0), //!<\n
      ADC3_IN4_PF6         = (ADC3_IN4            <<16)|( 5<<12)|( 6<<4)|( 0<<0), //!<\n
      ADC3_IN5_PF7         = (ADC3_IN5            <<16)|( 5<<12)|( 7<<4)|( 0<<0), //!<\n
      ADC3_IN6_PF8         = (ADC3_IN6            <<16)|( 5<<12)|( 8<<4)|( 0<<0), //!<\n
      ADC3_IN7_PF9         = (ADC3_IN7            <<16)|( 5<<12)|( 9<<4)|( 0<<0), //!<\n
      ADC3_IN8_PF10        = (ADC3_IN8            <<16)|( 5<<12)|(10<<4)|( 0<<0), //!<\n
      ADC3_IN9_PF3         = (ADC3_IN9            <<16)|( 5<<12)|( 3<<4)|( 0<<0), //!<\n
      CAN1_RX_PA11         = (CAN1_RX             <<16)|( 0<<12)|(11<<4)|( 9<<0), //!<\n
      CAN1_RX_PB8          = (CAN1_RX             <<16)|( 1<<12)|( 8<<4)|( 9<<0), //!<\n
      CAN1_RX_PD0          = (CAN1_RX             <<16)|( 3<<12)|( 0<<4)|( 9<<0), //!<\n
      CAN1_RX_PH14         = (CAN1_RX             <<16)|( 7<<12)|(14<<4)|( 9<<0), //!<\n
      CAN1_RX_PI9          = (CAN1_RX             <<16)|( 8<<12)|( 9<<4)|( 9<<0), //!<\n
      CAN1_TX_PA12         = (CAN1_TX             <<16)|( 0<<12)|(12<<4)|( 9<<0), //!<\n
      CAN1_TX_PB9          = (CAN1_TX             <<16)|( 1<<12)|( 9<<4)|( 9<<0), //!<\n
      CAN1_TX_PD1          = (CAN1_TX             <<16)|( 3<<12)|( 1<<4)|( 9<<0), //!<\n
      CAN1_TX_PH13         = (CAN1_TX             <<16)|( 7<<12)|(13<<4)|( 9<<0), //!<\n
      CAN2_RX_PB12         = (CAN2_RX             <<16)|( 1<<12)|(12<<4)|( 9<<0), //!<\n
      CAN2_RX_PB5          = (CAN2_RX             <<16)|( 1<<12)|( 5<<4)|( 9<<0), //!<\n
      CAN2_TX_PB13         = (CAN2_TX             <<16)|( 1<<12)|(13<<4)|( 9<<0), //!<\n
      CAN2_TX_PB6          = (CAN2_TX             <<16)|( 1<<12)|( 6<<4)|( 9<<0), //!<\n
      CAN3_RX_PA8          = (CAN3_RX             <<16)|( 0<<12)|( 8<<4)|(11<<0), //!<\n
      CAN3_RX_PB3          = (CAN3_RX             <<16)|( 1<<12)|( 3<<4)|(11<<0), //!<\n
      CAN3_TX_PA15         = (CAN3_TX             <<16)|( 0<<12)|(15<<4)|(11<<0), //!<\n
      CAN3_TX_PB4          = (CAN3_TX             <<16)|( 1<<12)|( 4<<4)|(11<<0), //!<\n
      CEC1_PA15            = (CEC1                <<16)|( 0<<12)|(15<<4)|( 4<<0), //!<\n
      CEC1_PB6             = (CEC1                <<16)|( 1<<12)|( 6<<4)|( 3<<0), //!<\n
      DAC_OUT1_PA4         = (DAC_OUT1            <<16)|( 0<<12)|( 4<<4)|( 0<<0), //!<\n
      DAC_OUT2_PA5         = (DAC_OUT2            <<16)|( 0<<12)|( 5<<4)|( 0<<0), //!<\n
      DCMI_D0_PA9          = (DCMI_D0             <<16)|( 0<<12)|( 9<<4)|(13<<0), //!<\n
      DCMI_D0_PC6          = (DCMI_D0             <<16)|( 2<<12)|( 6<<4)|(13<<0), //!<\n
      DCMI_D0_PH9          = (DCMI_D0             <<16)|( 7<<12)|( 9<<4)|(13<<0), //!<\n
      DCMI_D1_PA10         = (DCMI_D1             <<16)|( 0<<12)|(10<<4)|(13<<0), //!<\n
      DCMI_D1_PC7          = (DCMI_D1             <<16)|( 2<<12)|( 7<<4)|(13<<0), //!<\n
      DCMI_D1_PH10         = (DCMI_D1             <<16)|( 7<<12)|(10<<4)|(13<<0), //!<\n
      DCMI_D10_PB5         = (DCMI_D10            <<16)|( 1<<12)|( 5<<4)|(13<<0), //!<\n
      DCMI_D10_PD6         = (DCMI_D10            <<16)|( 3<<12)|( 6<<4)|(13<<0), //!<\n
      DCMI_D10_PI3         = (DCMI_D10            <<16)|( 8<<12)|( 3<<4)|(13<<0), //!<\n
      DCMI_D11_PD2         = (DCMI_D11            <<16)|( 3<<12)|( 2<<4)|(13<<0), //!<\n
      DCMI_D11_PF10        = (DCMI_D11            <<16)|( 5<<12)|(10<<4)|(13<<0), //!<\n
      DCMI_D11_PH15        = (DCMI_D11            <<16)|( 7<<12)|(15<<4)|(13<<0), //!<\n
      DCMI_D12_PF11        = (DCMI_D12            <<16)|( 5<<12)|(11<<4)|(13<<0), //!<\n
      DCMI_D12_PG6         = (DCMI_D12            <<16)|( 6<<12)|( 6<<4)|(13<<0), //!<\n
      DCMI_D13_PG15        = (DCMI_D13            <<16)|( 6<<12)|(15<<4)|(13<<0), //!<\n
      DCMI_D13_PG7         = (DCMI_D13            <<16)|( 6<<12)|( 7<<4)|(13<<0), //!<\n
      DCMI_D13_PI0         = (DCMI_D13            <<16)|( 8<<12)|( 0<<4)|(13<<0), //!<\n
      DCMI_D2_PC8          = (DCMI_D2             <<16)|( 2<<12)|( 8<<4)|(13<<0), //!<\n
      DCMI_D2_PE0          = (DCMI_D2             <<16)|( 4<<12)|( 0<<4)|(13<<0), //!<\n
      DCMI_D2_PG10         = (DCMI_D2             <<16)|( 6<<12)|(10<<4)|(13<<0), //!<\n
      DCMI_D2_PH11         = (DCMI_D2             <<16)|( 7<<12)|(11<<4)|(13<<0), //!<\n
      DCMI_D3_PC9          = (DCMI_D3             <<16)|( 2<<12)|( 9<<4)|(13<<0), //!<\n
      DCMI_D3_PE1          = (DCMI_D3             <<16)|( 4<<12)|( 1<<4)|(13<<0), //!<\n
      DCMI_D3_PG11         = (DCMI_D3             <<16)|( 6<<12)|(11<<4)|(13<<0), //!<\n
      DCMI_D3_PH12         = (DCMI_D3             <<16)|( 7<<12)|(12<<4)|(13<<0), //!<\n
      DCMI_D4_PC11         = (DCMI_D4             <<16)|( 2<<12)|(11<<4)|(13<<0), //!<\n
      DCMI_D4_PE4          = (DCMI_D4             <<16)|( 4<<12)|( 4<<4)|(13<<0), //!<\n
      DCMI_D4_PH14         = (DCMI_D4             <<16)|( 7<<12)|(14<<4)|(13<<0), //!<\n
      DCMI_D5_PB6          = (DCMI_D5             <<16)|( 1<<12)|( 6<<4)|(13<<0), //!<\n
      DCMI_D5_PD3          = (DCMI_D5             <<16)|( 3<<12)|( 3<<4)|(13<<0), //!<\n
      DCMI_D5_PI4          = (DCMI_D5             <<16)|( 8<<12)|( 4<<4)|(13<<0), //!<\n
      DCMI_D6_PB8          = (DCMI_D6             <<16)|( 1<<12)|( 8<<4)|(13<<0), //!<\n
      DCMI_D6_PE5          = (DCMI_D6             <<16)|( 4<<12)|( 5<<4)|(13<<0), //!<\n
      DCMI_D6_PI6          = (DCMI_D6             <<16)|( 8<<12)|( 6<<4)|(13<<0), //!<\n
      DCMI_D7_PB9          = (DCMI_D7             <<16)|( 1<<12)|( 9<<4)|(13<<0), //!<\n
      DCMI_D7_PE6          = (DCMI_D7             <<16)|( 4<<12)|( 6<<4)|(13<<0), //!<\n
      DCMI_D7_PI7          = (DCMI_D7             <<16)|( 8<<12)|( 7<<4)|(13<<0), //!<\n
      DCMI_D8_PC10         = (DCMI_D8             <<16)|( 2<<12)|(10<<4)|(13<<0), //!<\n
      DCMI_D8_PH6          = (DCMI_D8             <<16)|( 7<<12)|( 6<<4)|(13<<0), //!<\n
      DCMI_D8_PI1          = (DCMI_D8             <<16)|( 8<<12)|( 1<<4)|(13<<0), //!<\n
      DCMI_D9_PC12         = (DCMI_D9             <<16)|( 2<<12)|(12<<4)|(13<<0), //!<\n
      DCMI_D9_PH7          = (DCMI_D9             <<16)|( 7<<12)|( 7<<4)|(13<<0), //!<\n
      DCMI_D9_PI2          = (DCMI_D9             <<16)|( 8<<12)|( 2<<4)|(13<<0), //!<\n
      DCMI_HSYNC_PA4       = (DCMI_HSYNC          <<16)|( 0<<12)|( 4<<4)|(13<<0), //!<\n
      DCMI_HSYNC_PH8       = (DCMI_HSYNC          <<16)|( 7<<12)|( 8<<4)|(13<<0), //!<\n
      DCMI_PIXCLK_PA6      = (DCMI_PIXCLK         <<16)|( 0<<12)|( 6<<4)|(13<<0), //!<\n
      DCMI_VSYNC_PB7       = (DCMI_VSYNC          <<16)|( 1<<12)|( 7<<4)|(13<<0), //!<\n
      DCMI_VSYNC_PG9       = (DCMI_VSYNC          <<16)|( 6<<12)|( 9<<4)|(13<<0), //!<\n
      DCMI_VSYNC_PI5       = (DCMI_VSYNC          <<16)|( 8<<12)|( 5<<4)|(13<<0), //!<\n
      DFSDM1_CKIN0_PC0     = (DFSDM1_CKIN0        <<16)|( 2<<12)|( 0<<4)|( 3<<0), //!<\n
      DFSDM1_CKIN0_PD4     = (DFSDM1_CKIN0        <<16)|( 3<<12)|( 4<<4)|( 6<<0), //!<\n
      DFSDM1_CKIN1_PB13    = (DFSDM1_CKIN1        <<16)|( 1<<12)|(13<<4)|( 6<<0), //!<\n
      DFSDM1_CKIN1_PB2     = (DFSDM1_CKIN1        <<16)|( 1<<12)|( 2<<4)|(10<<0), //!<\n
      DFSDM1_CKIN1_PC2     = (DFSDM1_CKIN1        <<16)|( 2<<12)|( 2<<4)|( 3<<0), //!<\n
      DFSDM1_CKIN1_PD7     = (DFSDM1_CKIN1        <<16)|( 3<<12)|( 7<<4)|( 6<<0), //!<\n
      DFSDM1_CKIN2_PB15    = (DFSDM1_CKIN2        <<16)|( 1<<12)|(15<<4)|( 6<<0), //!<\n
      DFSDM1_CKIN2_PC4     = (DFSDM1_CKIN2        <<16)|( 2<<12)|( 4<<4)|( 3<<0), //!<\n
      DFSDM1_CKIN2_PE8     = (DFSDM1_CKIN2        <<16)|( 4<<12)|( 8<<4)|( 6<<0), //!<\n
      DFSDM1_CKIN3_PC6     = (DFSDM1_CKIN3        <<16)|( 2<<12)|( 6<<4)|( 7<<0), //!<\n
      DFSDM1_CKIN3_PD8     = (DFSDM1_CKIN3        <<16)|( 3<<12)|( 8<<4)|( 3<<0), //!<\n
      DFSDM1_CKIN3_PE5     = (DFSDM1_CKIN3        <<16)|( 4<<12)|( 5<<4)|(10<<0), //!<\n
      DFSDM1_CKIN4_PC1     = (DFSDM1_CKIN4        <<16)|( 2<<12)|( 1<<4)|(10<<0), //!<\n
      DFSDM1_CKIN4_PD6     = (DFSDM1_CKIN4        <<16)|( 3<<12)|( 6<<4)|( 3<<0), //!<\n
      DFSDM1_CKIN4_PE11    = (DFSDM1_CKIN4        <<16)|( 4<<12)|(11<<4)|( 6<<0), //!<\n
      DFSDM1_CKIN5_PB7     = (DFSDM1_CKIN5        <<16)|( 1<<12)|( 7<<4)|( 6<<0), //!<\n
      DFSDM1_CKIN5_PC10    = (DFSDM1_CKIN5        <<16)|( 2<<12)|(10<<4)|( 3<<0), //!<\n
      DFSDM1_CKIN5_PE13    = (DFSDM1_CKIN5        <<16)|( 4<<12)|(13<<4)|( 6<<0), //!<\n
      DFSDM1_CKIN6_PD0     = (DFSDM1_CKIN6        <<16)|( 3<<12)|( 0<<4)|( 3<<0), //!<\n
      DFSDM1_CKIN6_PF14    = (DFSDM1_CKIN6        <<16)|( 5<<12)|(14<<4)|( 6<<0), //!<\n
      DFSDM1_CKIN7_PB11    = (DFSDM1_CKIN7        <<16)|( 1<<12)|(11<<4)|( 6<<0), //!<\n
      DFSDM1_CKIN7_PB8     = (DFSDM1_CKIN7        <<16)|( 1<<12)|( 8<<4)|( 6<<0), //!<\n
      DFSDM1_CKIN7_PD1     = (DFSDM1_CKIN7        <<16)|( 3<<12)|( 1<<4)|( 6<<0), //!<\n
      DFSDM1_CKOUT_PB0     = (DFSDM1_CKOUT        <<16)|( 1<<12)|( 0<<4)|( 6<<0), //!<\n
      DFSDM1_CKOUT_PC2     = (DFSDM1_CKOUT        <<16)|( 2<<12)|( 2<<4)|( 6<<0), //!<\n
      DFSDM1_CKOUT_PD10    = (DFSDM1_CKOUT        <<16)|( 3<<12)|(10<<4)|( 3<<0), //!<\n
      DFSDM1_CKOUT_PD3     = (DFSDM1_CKOUT        <<16)|( 3<<12)|( 3<<4)|( 3<<0), //!<\n
      DFSDM1_CKOUT_PE9     = (DFSDM1_CKOUT        <<16)|( 4<<12)|( 9<<4)|( 6<<0), //!<\n
      DFSDM1_DATIN0_PC1    = (DFSDM1_DATIN0       <<16)|( 2<<12)|( 1<<4)|( 3<<0), //!<\n
      DFSDM1_DATIN0_PD3    = (DFSDM1_DATIN0       <<16)|( 3<<12)|( 3<<4)|( 6<<0), //!<\n
      DFSDM1_DATIN1_PB1    = (DFSDM1_DATIN1       <<16)|( 1<<12)|( 1<<4)|( 6<<0), //!<\n
      DFSDM1_DATIN1_PB12   = (DFSDM1_DATIN1       <<16)|( 1<<12)|(12<<4)|( 6<<0), //!<\n
      DFSDM1_DATIN1_PC3    = (DFSDM1_DATIN1       <<16)|( 2<<12)|( 3<<4)|( 3<<0), //!<\n
      DFSDM1_DATIN1_PD6    = (DFSDM1_DATIN1       <<16)|( 3<<12)|( 6<<4)|(10<<0), //!<\n
      DFSDM1_DATIN2_PB14   = (DFSDM1_DATIN2       <<16)|( 1<<12)|(14<<4)|( 6<<0), //!<\n
      DFSDM1_DATIN2_PC5    = (DFSDM1_DATIN2       <<16)|( 2<<12)|( 5<<4)|( 3<<0), //!<\n
      DFSDM1_DATIN2_PE7    = (DFSDM1_DATIN2       <<16)|( 4<<12)|( 7<<4)|( 6<<0), //!<\n
      DFSDM1_DATIN3_PC7    = (DFSDM1_DATIN3       <<16)|( 2<<12)|( 7<<4)|( 7<<0), //!<\n
      DFSDM1_DATIN3_PD9    = (DFSDM1_DATIN3       <<16)|( 3<<12)|( 9<<4)|( 3<<0), //!<\n
      DFSDM1_DATIN3_PE4    = (DFSDM1_DATIN3       <<16)|( 4<<12)|( 4<<4)|(10<<0), //!<\n
      DFSDM1_DATIN4_PC0    = (DFSDM1_DATIN4       <<16)|( 2<<12)|( 0<<4)|( 6<<0), //!<\n
      DFSDM1_DATIN4_PD7    = (DFSDM1_DATIN4       <<16)|( 3<<12)|( 7<<4)|( 3<<0), //!<\n
      DFSDM1_DATIN4_PE10   = (DFSDM1_DATIN4       <<16)|( 4<<12)|(10<<4)|( 6<<0), //!<\n
      DFSDM1_DATIN5_PB6    = (DFSDM1_DATIN5       <<16)|( 1<<12)|( 6<<4)|( 6<<0), //!<\n
      DFSDM1_DATIN5_PC11   = (DFSDM1_DATIN5       <<16)|( 2<<12)|(11<<4)|( 3<<0), //!<\n
      DFSDM1_DATIN5_PE12   = (DFSDM1_DATIN5       <<16)|( 4<<12)|(12<<4)|( 6<<0), //!<\n
      DFSDM1_DATIN6_PD1    = (DFSDM1_DATIN6       <<16)|( 3<<12)|( 1<<4)|( 3<<0), //!<\n
      DFSDM1_DATIN6_PF13   = (DFSDM1_DATIN6       <<16)|( 5<<12)|(13<<4)|( 6<<0), //!<\n
      DFSDM1_DATIN7_PB10   = (DFSDM1_DATIN7       <<16)|( 1<<12)|(10<<4)|( 6<<0), //!<\n
      DFSDM1_DATIN7_PB9    = (DFSDM1_DATIN7       <<16)|( 1<<12)|( 9<<4)|( 6<<0), //!<\n
      DFSDM1_DATIN7_PD0    = (DFSDM1_DATIN7       <<16)|( 3<<12)|( 0<<4)|( 6<<0), //!<\n
      DSIHOST_TE_PB11      = (DSIHOST_TE          <<16)|( 1<<12)|(11<<4)|(13<<0), //!<\n
      DSIHOST_TE_PJ2       = (DSIHOST_TE          <<16)|( 9<<12)|( 2<<4)|(13<<0), //!<\n
      ETH_COL_PA3          = (ETH_COL             <<16)|( 0<<12)|( 3<<4)|(11<<0), //!<\n
      ETH_COL_PH3          = (ETH_COL             <<16)|( 7<<12)|( 3<<4)|(11<<0), //!<\n
      ETH_CRS_PA0          = (ETH_CRS             <<16)|( 0<<12)|( 0<<4)|(11<<0), //!<\n
      ETH_CRS_PH2          = (ETH_CRS             <<16)|( 7<<12)|( 2<<4)|(11<<0), //!<\n
      ETH_CRS_DV_PA7       = (ETH_CRS_DV          <<16)|( 0<<12)|( 7<<4)|(11<<0), //!<\n
      ETH_MDC_PC1          = (ETH_MDC             <<16)|( 2<<12)|( 1<<4)|(11<<0), //!<\n
      ETH_MDIO_PA2         = (ETH_MDIO            <<16)|( 0<<12)|( 2<<4)|(11<<0), //!<\n
      ETH_PPS_OUT_PB5      = (ETH_PPS_OUT         <<16)|( 1<<12)|( 5<<4)|(11<<0), //!<\n
      ETH_PPS_OUT_PG8      = (ETH_PPS_OUT         <<16)|( 6<<12)|( 8<<4)|(11<<0), //!<\n
      ETH_REF_CLK_PA1      = (ETH_REF_CLK         <<16)|( 0<<12)|( 1<<4)|(11<<0), //!<\n
      ETH_RXD0_PC4         = (ETH_RXD0            <<16)|( 2<<12)|( 4<<4)|(11<<0), //!<\n
      ETH_RXD1_PC5         = (ETH_RXD1            <<16)|( 2<<12)|( 5<<4)|(11<<0), //!<\n
      ETH_RXD2_PB0         = (ETH_RXD2            <<16)|( 1<<12)|( 0<<4)|(11<<0), //!<\n
      ETH_RXD2_PH6         = (ETH_RXD2            <<16)|( 7<<12)|( 6<<4)|(11<<0), //!<\n
      ETH_RXD3_PB1         = (ETH_RXD3            <<16)|( 1<<12)|( 1<<4)|(11<<0), //!<\n
      ETH_RXD3_PH7         = (ETH_RXD3            <<16)|( 7<<12)|( 7<<4)|(11<<0), //!<\n
      ETH_RX_CLK_PA1       = (ETH_RX_CLK          <<16)|( 0<<12)|( 1<<4)|(11<<0), //!<\n
      ETH_RX_DV_PA7        = (ETH_RX_DV           <<16)|( 0<<12)|( 7<<4)|(11<<0), //!<\n
      ETH_RX_ER_PB10       = (ETH_RX_ER           <<16)|( 1<<12)|(10<<4)|(11<<0), //!<\n
      ETH_RX_ER_PI10       = (ETH_RX_ER           <<16)|( 8<<12)|(10<<4)|(11<<0), //!<\n
      ETH_TXD0_PB12        = (ETH_TXD0            <<16)|( 1<<12)|(12<<4)|(11<<0), //!<\n
      ETH_TXD0_PG13        = (ETH_TXD0            <<16)|( 6<<12)|(13<<4)|(11<<0), //!<\n
      ETH_TXD1_PB13        = (ETH_TXD1            <<16)|( 1<<12)|(13<<4)|(11<<0), //!<\n
      ETH_TXD1_PG14        = (ETH_TXD1            <<16)|( 6<<12)|(14<<4)|(11<<0), //!<\n
      ETH_TXD2_PC2         = (ETH_TXD2            <<16)|( 2<<12)|( 2<<4)|(11<<0), //!<\n
      ETH_TXD3_PB8         = (ETH_TXD3            <<16)|( 1<<12)|( 8<<4)|(11<<0), //!<\n
      ETH_TXD3_PE2         = (ETH_TXD3            <<16)|( 4<<12)|( 2<<4)|(11<<0), //!<\n
      ETH_TX_CLK_PC3       = (ETH_TX_CLK          <<16)|( 2<<12)|( 3<<4)|(11<<0), //!<\n
      ETH_TX_EN_PB11       = (ETH_TX_EN           <<16)|( 1<<12)|(11<<4)|(11<<0), //!<\n
      ETH_TX_EN_PG11       = (ETH_TX_EN           <<16)|( 6<<12)|(11<<4)|(11<<0), //!<\n
      FMC_A0_PF0           = (FMC_A0              <<16)|( 5<<12)|( 0<<4)|(12<<0), //!<\n
      FMC_A1_PF1           = (FMC_A1              <<16)|( 5<<12)|( 1<<4)|(12<<0), //!<\n
      FMC_A10_PG0          = (FMC_A10             <<16)|( 6<<12)|( 0<<4)|(12<<0), //!<\n
      FMC_A11_PG1          = (FMC_A11             <<16)|( 6<<12)|( 1<<4)|(12<<0), //!<\n
      FMC_A12_PG2          = (FMC_A12             <<16)|( 6<<12)|( 2<<4)|(12<<0), //!<\n
      FMC_A13_PG3          = (FMC_A13             <<16)|( 6<<12)|( 3<<4)|(12<<0), //!<\n
      FMC_A14_PG4          = (FMC_A14             <<16)|( 6<<12)|( 4<<4)|(12<<0), //!<\n
      FMC_A15_PG5          = (FMC_A15             <<16)|( 6<<12)|( 5<<4)|(12<<0), //!<\n
      FMC_A16_PD11         = (FMC_A16             <<16)|( 3<<12)|(11<<4)|(12<<0), //!<\n
      FMC_A17_PD12         = (FMC_A17             <<16)|( 3<<12)|(12<<4)|(12<<0), //!<\n
      FMC_A18_PD13         = (FMC_A18             <<16)|( 3<<12)|(13<<4)|(12<<0), //!<\n
      FMC_A19_PE3          = (FMC_A19             <<16)|( 4<<12)|( 3<<4)|(12<<0), //!<\n
      FMC_A2_PF2           = (FMC_A2              <<16)|( 5<<12)|( 2<<4)|(12<<0), //!<\n
      FMC_A20_PE4          = (FMC_A20             <<16)|( 4<<12)|( 4<<4)|(12<<0), //!<\n
      FMC_A21_PE5          = (FMC_A21             <<16)|( 4<<12)|( 5<<4)|(12<<0), //!<\n
      FMC_A22_PE6          = (FMC_A22             <<16)|( 4<<12)|( 6<<4)|(12<<0), //!<\n
      FMC_A23_PE2          = (FMC_A23             <<16)|( 4<<12)|( 2<<4)|(12<<0), //!<\n
      FMC_A24_PG13         = (FMC_A24             <<16)|( 6<<12)|(13<<4)|(12<<0), //!<\n
      FMC_A25_PG14         = (FMC_A25             <<16)|( 6<<12)|(14<<4)|(12<<0), //!<\n
      FMC_A3_PF3           = (FMC_A3              <<16)|( 5<<12)|( 3<<4)|(12<<0), //!<\n
      FMC_A4_PF4           = (FMC_A4              <<16)|( 5<<12)|( 4<<4)|(12<<0), //!<\n
      FMC_A5_PF5           = (FMC_A5              <<16)|( 5<<12)|( 5<<4)|(12<<0), //!<\n
      FMC_A6_PF12          = (FMC_A6              <<16)|( 5<<12)|(12<<4)|(12<<0), //!<\n
      FMC_A7_PF13          = (FMC_A7              <<16)|( 5<<12)|(13<<4)|(12<<0), //!<\n
      FMC_A8_PF14          = (FMC_A8              <<16)|( 5<<12)|(14<<4)|(12<<0), //!<\n
      FMC_A9_PF15          = (FMC_A9              <<16)|( 5<<12)|(15<<4)|(12<<0), //!<\n
      FMC_ALE_PD12         = (FMC_ALE             <<16)|( 3<<12)|(12<<4)|(12<<0), //!<\n
      FMC_BA0_PG4          = (FMC_BA0             <<16)|( 6<<12)|( 4<<4)|(12<<0), //!<\n
      FMC_BA1_PG5          = (FMC_BA1             <<16)|( 6<<12)|( 5<<4)|(12<<0), //!<\n
      FMC_CLE_PD11         = (FMC_CLE             <<16)|( 3<<12)|(11<<4)|(12<<0), //!<\n
      FMC_CLK_PD3          = (FMC_CLK             <<16)|( 3<<12)|( 3<<4)|(12<<0), //!<\n
      FMC_D0_PD14          = (FMC_D0              <<16)|( 3<<12)|(14<<4)|(12<<0), //!<\n
      FMC_D1_PD15          = (FMC_D1              <<16)|( 3<<12)|(15<<4)|(12<<0), //!<\n
      FMC_D10_PE13         = (FMC_D10             <<16)|( 4<<12)|(13<<4)|(12<<0), //!<\n
      FMC_D11_PE14         = (FMC_D11             <<16)|( 4<<12)|(14<<4)|(12<<0), //!<\n
      FMC_D12_PE15         = (FMC_D12             <<16)|( 4<<12)|(15<<4)|(12<<0), //!<\n
      FMC_D13_PD8          = (FMC_D13             <<16)|( 3<<12)|( 8<<4)|(12<<0), //!<\n
      FMC_D14_PD9          = (FMC_D14             <<16)|( 3<<12)|( 9<<4)|(12<<0), //!<\n
      FMC_D15_PD10         = (FMC_D15             <<16)|( 3<<12)|(10<<4)|(12<<0), //!<\n
      FMC_D16_PH8          = (FMC_D16             <<16)|( 7<<12)|( 8<<4)|(12<<0), //!<\n
      FMC_D17_PH9          = (FMC_D17             <<16)|( 7<<12)|( 9<<4)|(12<<0), //!<\n
      FMC_D18_PH10         = (FMC_D18             <<16)|( 7<<12)|(10<<4)|(12<<0), //!<\n
      FMC_D19_PH11         = (FMC_D19             <<16)|( 7<<12)|(11<<4)|(12<<0), //!<\n
      FMC_D2_PD0           = (FMC_D2              <<16)|( 3<<12)|( 0<<4)|(12<<0), //!<\n
      FMC_D20_PH12         = (FMC_D20             <<16)|( 7<<12)|(12<<4)|(12<<0), //!<\n
      FMC_D21_PH13         = (FMC_D21             <<16)|( 7<<12)|(13<<4)|(12<<0), //!<\n
      FMC_D22_PH14         = (FMC_D22             <<16)|( 7<<12)|(14<<4)|(12<<0), //!<\n
      FMC_D23_PH15         = (FMC_D23             <<16)|( 7<<12)|(15<<4)|(12<<0), //!<\n
      FMC_D24_PI0          = (FMC_D24             <<16)|( 8<<12)|( 0<<4)|(12<<0), //!<\n
      FMC_D25_PI1          = (FMC_D25             <<16)|( 8<<12)|( 1<<4)|(12<<0), //!<\n
      FMC_D26_PI2          = (FMC_D26             <<16)|( 8<<12)|( 2<<4)|(12<<0), //!<\n
      FMC_D27_PI3          = (FMC_D27             <<16)|( 8<<12)|( 3<<4)|(12<<0), //!<\n
      FMC_D28_PI6          = (FMC_D28             <<16)|( 8<<12)|( 6<<4)|(12<<0), //!<\n
      FMC_D29_PI7          = (FMC_D29             <<16)|( 8<<12)|( 7<<4)|(12<<0), //!<\n
      FMC_D3_PD1           = (FMC_D3              <<16)|( 3<<12)|( 1<<4)|(12<<0), //!<\n
      FMC_D30_PI9          = (FMC_D30             <<16)|( 8<<12)|( 9<<4)|(12<<0), //!<\n
      FMC_D31_PI10         = (FMC_D31             <<16)|( 8<<12)|(10<<4)|(12<<0), //!<\n
      FMC_D4_PE7           = (FMC_D4              <<16)|( 4<<12)|( 7<<4)|(12<<0), //!<\n
      FMC_D5_PE8           = (FMC_D5              <<16)|( 4<<12)|( 8<<4)|(12<<0), //!<\n
      FMC_D6_PE9           = (FMC_D6              <<16)|( 4<<12)|( 9<<4)|(12<<0), //!<\n
      FMC_D7_PE10          = (FMC_D7              <<16)|( 4<<12)|(10<<4)|(12<<0), //!<\n
      FMC_D8_PE11          = (FMC_D8              <<16)|( 4<<12)|(11<<4)|(12<<0), //!<\n
      FMC_D9_PE12          = (FMC_D9              <<16)|( 4<<12)|(12<<4)|(12<<0), //!<\n
      FMC_DA0_PD14         = (FMC_DA0             <<16)|( 3<<12)|(14<<4)|(12<<0), //!<\n
      FMC_DA1_PD15         = (FMC_DA1             <<16)|( 3<<12)|(15<<4)|(12<<0), //!<\n
      FMC_DA10_PE13        = (FMC_DA10            <<16)|( 4<<12)|(13<<4)|(12<<0), //!<\n
      FMC_DA11_PE14        = (FMC_DA11            <<16)|( 4<<12)|(14<<4)|(12<<0), //!<\n
      FMC_DA12_PE15        = (FMC_DA12            <<16)|( 4<<12)|(15<<4)|(12<<0), //!<\n
      FMC_DA13_PD8         = (FMC_DA13            <<16)|( 3<<12)|( 8<<4)|(12<<0), //!<\n
      FMC_DA14_PD9         = (FMC_DA14            <<16)|( 3<<12)|( 9<<4)|(12<<0), //!<\n
      FMC_DA15_PD10        = (FMC_DA15            <<16)|( 3<<12)|(10<<4)|(12<<0), //!<\n
      FMC_DA2_PD0          = (FMC_DA2             <<16)|( 3<<12)|( 0<<4)|(12<<0), //!<\n
      FMC_DA3_PD1          = (FMC_DA3             <<16)|( 3<<12)|( 1<<4)|(12<<0), //!<\n
      FMC_DA4_PE7          = (FMC_DA4             <<16)|( 4<<12)|( 7<<4)|(12<<0), //!<\n
      FMC_DA5_PE8          = (FMC_DA5             <<16)|( 4<<12)|( 8<<4)|(12<<0), //!<\n
      FMC_DA6_PE9          = (FMC_DA6             <<16)|( 4<<12)|( 9<<4)|(12<<0), //!<\n
      FMC_DA7_PE10         = (FMC_DA7             <<16)|( 4<<12)|(10<<4)|(12<<0), //!<\n
      FMC_DA8_PE11         = (FMC_DA8             <<16)|( 4<<12)|(11<<4)|(12<<0), //!<\n
      FMC_DA9_PE12         = (FMC_DA9             <<16)|( 4<<12)|(12<<4)|(12<<0), //!<\n
      FMC_INT_PG7          = (FMC_INT             <<16)|( 6<<12)|( 7<<4)|(12<<0), //!<\n
      FMC_NBL0_PE0         = (FMC_NBL0            <<16)|( 4<<12)|( 0<<4)|(12<<0), //!<\n
      FMC_NBL1_PE1         = (FMC_NBL1            <<16)|( 4<<12)|( 1<<4)|(12<<0), //!<\n
      FMC_NBL2_PI4         = (FMC_NBL2            <<16)|( 8<<12)|( 4<<4)|(12<<0), //!<\n
      FMC_NBL3_PI5         = (FMC_NBL3            <<16)|( 8<<12)|( 5<<4)|(12<<0), //!<\n
      FMC_NCE_PC8          = (FMC_NCE             <<16)|( 2<<12)|( 8<<4)|( 9<<0), //!<\n
      FMC_NCE_PG9          = (FMC_NCE             <<16)|( 6<<12)|( 9<<4)|(12<<0), //!<\n
      FMC_NE1_PC7          = (FMC_NE1             <<16)|( 2<<12)|( 7<<4)|( 9<<0), //!<\n
      FMC_NE1_PD7          = (FMC_NE1             <<16)|( 3<<12)|( 7<<4)|(12<<0), //!<\n
      FMC_NE2_PC8          = (FMC_NE2             <<16)|( 2<<12)|( 8<<4)|( 9<<0), //!<\n
      FMC_NE2_PG9          = (FMC_NE2             <<16)|( 6<<12)|( 9<<4)|(12<<0), //!<\n
      FMC_NE3_PG10         = (FMC_NE3             <<16)|( 6<<12)|(10<<4)|(12<<0), //!<\n
      FMC_NE3_PG6          = (FMC_NE3             <<16)|( 6<<12)|( 6<<4)|(12<<0), //!<\n
      FMC_NE4_PG12         = (FMC_NE4             <<16)|( 6<<12)|(12<<4)|(12<<0), //!<\n
      FMC_NL_PB7           = (FMC_NL              <<16)|( 1<<12)|( 7<<4)|(12<<0), //!<\n
      FMC_NOE_PD4          = (FMC_NOE             <<16)|( 3<<12)|( 4<<4)|(12<<0), //!<\n
      FMC_NWAIT_PC6        = (FMC_NWAIT           <<16)|( 2<<12)|( 6<<4)|( 9<<0), //!<\n
      FMC_NWAIT_PD6        = (FMC_NWAIT           <<16)|( 3<<12)|( 6<<4)|(12<<0), //!<\n
      FMC_NWE_PD5          = (FMC_NWE             <<16)|( 3<<12)|( 5<<4)|(12<<0), //!<\n
      FMC_SDCKE0_PC3       = (FMC_SDCKE0          <<16)|( 2<<12)|( 3<<4)|(12<<0), //!<\n
      FMC_SDCKE0_PC5       = (FMC_SDCKE0          <<16)|( 2<<12)|( 5<<4)|(12<<0), //!<\n
      FMC_SDCKE0_PH2       = (FMC_SDCKE0          <<16)|( 7<<12)|( 2<<4)|(12<<0), //!<\n
      FMC_SDCKE1_PB5       = (FMC_SDCKE1          <<16)|( 1<<12)|( 5<<4)|(12<<0), //!<\n
      FMC_SDCKE1_PH7       = (FMC_SDCKE1          <<16)|( 7<<12)|( 7<<4)|(12<<0), //!<\n
      FMC_SDCLK_PG8        = (FMC_SDCLK           <<16)|( 6<<12)|( 8<<4)|(12<<0), //!<\n
      FMC_SDNCAS_PG15      = (FMC_SDNCAS          <<16)|( 6<<12)|(15<<4)|(12<<0), //!<\n
      FMC_SDNE0_PC2        = (FMC_SDNE0           <<16)|( 2<<12)|( 2<<4)|(12<<0), //!<\n
      FMC_SDNE0_PC4        = (FMC_SDNE0           <<16)|( 2<<12)|( 4<<4)|(12<<0), //!<\n
      FMC_SDNE0_PH3        = (FMC_SDNE0           <<16)|( 7<<12)|( 3<<4)|(12<<0), //!<\n
      FMC_SDNE1_PB6        = (FMC_SDNE1           <<16)|( 1<<12)|( 6<<4)|(12<<0), //!<\n
      FMC_SDNE1_PH6        = (FMC_SDNE1           <<16)|( 7<<12)|( 6<<4)|(12<<0), //!<\n
      FMC_SDNRAS_PF11      = (FMC_SDNRAS          <<16)|( 5<<12)|(11<<4)|(12<<0), //!<\n
      FMC_SDNWE_PA7        = (FMC_SDNWE           <<16)|( 0<<12)|( 7<<4)|(12<<0), //!<\n
      FMC_SDNWE_PC0        = (FMC_SDNWE           <<16)|( 2<<12)|( 0<<4)|(12<<0), //!<\n
      FMC_SDNWE_PH5        = (FMC_SDNWE           <<16)|( 7<<12)|( 5<<4)|(12<<0), //!<\n
      I2C1_SCL_PB6         = (I2C1_SCL            <<16)|( 1<<12)|( 6<<4)|( 4<<0), //!<\n
      I2C1_SCL_PB8         = (I2C1_SCL            <<16)|( 1<<12)|( 8<<4)|( 4<<0), //!<\n
      I2C1_SDA_PB7         = (I2C1_SDA            <<16)|( 1<<12)|( 7<<4)|( 4<<0), //!<\n
      I2C1_SDA_PB9         = (I2C1_SDA            <<16)|( 1<<12)|( 9<<4)|( 4<<0), //!<\n
      I2C1_SMBA_PB5        = (I2C1_SMBA           <<16)|( 1<<12)|( 5<<4)|( 4<<0), //!<\n
      I2C2_SCL_PB10        = (I2C2_SCL            <<16)|( 1<<12)|(10<<4)|( 4<<0), //!<\n
      I2C2_SCL_PF1         = (I2C2_SCL            <<16)|( 5<<12)|( 1<<4)|( 4<<0), //!<\n
      I2C2_SCL_PH4         = (I2C2_SCL            <<16)|( 7<<12)|( 4<<4)|( 4<<0), //!<\n
      I2C2_SDA_PB11        = (I2C2_SDA            <<16)|( 1<<12)|(11<<4)|( 4<<0), //!<\n
      I2C2_SDA_PF0         = (I2C2_SDA            <<16)|( 5<<12)|( 0<<4)|( 4<<0), //!<\n
      I2C2_SDA_PH5         = (I2C2_SDA            <<16)|( 7<<12)|( 5<<4)|( 4<<0), //!<\n
      I2C2_SMBA_PB12       = (I2C2_SMBA           <<16)|( 1<<12)|(12<<4)|( 4<<0), //!<\n
      I2C2_SMBA_PF2        = (I2C2_SMBA           <<16)|( 5<<12)|( 2<<4)|( 4<<0), //!<\n
      I2C2_SMBA_PH6        = (I2C2_SMBA           <<16)|( 7<<12)|( 6<<4)|( 4<<0), //!<\n
      I2C3_SCL_PA8         = (I2C3_SCL            <<16)|( 0<<12)|( 8<<4)|( 4<<0), //!<\n
      I2C3_SCL_PH7         = (I2C3_SCL            <<16)|( 7<<12)|( 7<<4)|( 4<<0), //!<\n
      I2C3_SDA_PC9         = (I2C3_SDA            <<16)|( 2<<12)|( 9<<4)|( 4<<0), //!<\n
      I2C3_SDA_PH8         = (I2C3_SDA            <<16)|( 7<<12)|( 8<<4)|( 4<<0), //!<\n
      I2C3_SMBA_PA9        = (I2C3_SMBA           <<16)|( 0<<12)|( 9<<4)|( 4<<0), //!<\n
      I2C3_SMBA_PH9        = (I2C3_SMBA           <<16)|( 7<<12)|( 9<<4)|( 4<<0), //!<\n
      I2C4_SCL_PB6         = (I2C4_SCL            <<16)|( 1<<12)|( 6<<4)|(11<<0), //!<\n
      I2C4_SCL_PB8         = (I2C4_SCL            <<16)|( 1<<12)|( 8<<4)|( 1<<0), //!<\n
      I2C4_SCL_PD12        = (I2C4_SCL            <<16)|( 3<<12)|(12<<4)|( 4<<0), //!<\n
      I2C4_SCL_PF14        = (I2C4_SCL            <<16)|( 5<<12)|(14<<4)|( 4<<0), //!<\n
      I2C4_SCL_PH11        = (I2C4_SCL            <<16)|( 7<<12)|(11<<4)|( 4<<0), //!<\n
      I2C4_SDA_PB7         = (I2C4_SDA            <<16)|( 1<<12)|( 7<<4)|(11<<0), //!<\n
      I2C4_SDA_PB9         = (I2C4_SDA            <<16)|( 1<<12)|( 9<<4)|( 1<<0), //!<\n
      I2C4_SDA_PD13        = (I2C4_SDA            <<16)|( 3<<12)|(13<<4)|( 4<<0), //!<\n
      I2C4_SDA_PF15        = (I2C4_SDA            <<16)|( 5<<12)|(15<<4)|( 4<<0), //!<\n
      I2C4_SDA_PH12        = (I2C4_SDA            <<16)|( 7<<12)|(12<<4)|( 4<<0), //!<\n
      I2C4_SMBA_PB9        = (I2C4_SMBA           <<16)|( 1<<12)|( 9<<4)|(11<<0), //!<\n
      I2C4_SMBA_PD11       = (I2C4_SMBA           <<16)|( 3<<12)|(11<<4)|( 4<<0), //!<\n
      I2C4_SMBA_PF13       = (I2C4_SMBA           <<16)|( 5<<12)|(13<<4)|( 4<<0), //!<\n
      I2C4_SMBA_PH10       = (I2C4_SMBA           <<16)|( 7<<12)|(10<<4)|( 4<<0), //!<\n
      I2S1_CK_PA5          = (I2S1_CK             <<16)|( 0<<12)|( 5<<4)|( 5<<0), //!<\n
      I2S1_CK_PB3          = (I2S1_CK             <<16)|( 1<<12)|( 3<<4)|( 5<<0), //!<\n
      I2S1_CK_PG11         = (I2S1_CK             <<16)|( 6<<12)|(11<<4)|( 5<<0), //!<\n
      I2S1_MCK_PC4         = (I2S1_MCK            <<16)|( 2<<12)|( 4<<4)|( 5<<0), //!<\n
      I2S1_SD_PA7          = (I2S1_SD             <<16)|( 0<<12)|( 7<<4)|( 5<<0), //!<\n
      I2S1_SD_PB5          = (I2S1_SD             <<16)|( 1<<12)|( 5<<4)|( 5<<0), //!<\n
      I2S1_SD_PD7          = (I2S1_SD             <<16)|( 3<<12)|( 7<<4)|( 5<<0), //!<\n
      I2S1_WS_PA15         = (I2S1_WS             <<16)|( 0<<12)|(15<<4)|( 5<<0), //!<\n
      I2S1_WS_PA4          = (I2S1_WS             <<16)|( 0<<12)|( 4<<4)|( 5<<0), //!<\n
      I2S1_WS_PG10         = (I2S1_WS             <<16)|( 6<<12)|(10<<4)|( 5<<0), //!<\n
      I2S2_CK_PA12         = (I2S2_CK             <<16)|( 0<<12)|(12<<4)|( 5<<0), //!<\n
      I2S2_CK_PA9          = (I2S2_CK             <<16)|( 0<<12)|( 9<<4)|( 5<<0), //!<\n
      I2S2_CK_PB10         = (I2S2_CK             <<16)|( 1<<12)|(10<<4)|( 5<<0), //!<\n
      I2S2_CK_PB13         = (I2S2_CK             <<16)|( 1<<12)|(13<<4)|( 5<<0), //!<\n
      I2S2_CK_PD3          = (I2S2_CK             <<16)|( 3<<12)|( 3<<4)|( 5<<0), //!<\n
      I2S2_CK_PI1          = (I2S2_CK             <<16)|( 8<<12)|( 1<<4)|( 5<<0), //!<\n
      I2S2_MCK_PC6         = (I2S2_MCK            <<16)|( 2<<12)|( 6<<4)|( 5<<0), //!<\n
      I2S2_SD_PB15         = (I2S2_SD             <<16)|( 1<<12)|(15<<4)|( 5<<0), //!<\n
      I2S2_SD_PC1          = (I2S2_SD             <<16)|( 2<<12)|( 1<<4)|( 5<<0), //!<\n
      I2S2_SD_PC3          = (I2S2_SD             <<16)|( 2<<12)|( 3<<4)|( 5<<0), //!<\n
      I2S2_SD_PI3          = (I2S2_SD             <<16)|( 8<<12)|( 3<<4)|( 5<<0), //!<\n
      I2S2_WS_PA11         = (I2S2_WS             <<16)|( 0<<12)|(11<<4)|( 5<<0), //!<\n
      I2S2_WS_PB12         = (I2S2_WS             <<16)|( 1<<12)|(12<<4)|( 5<<0), //!<\n
      I2S2_WS_PB4          = (I2S2_WS             <<16)|( 1<<12)|( 4<<4)|( 7<<0), //!<\n
      I2S2_WS_PB9          = (I2S2_WS             <<16)|( 1<<12)|( 9<<4)|( 5<<0), //!<\n
      I2S2_WS_PI0          = (I2S2_WS             <<16)|( 8<<12)|( 0<<4)|( 5<<0), //!<\n
      I2S3_CK_PB3          = (I2S3_CK             <<16)|( 1<<12)|( 3<<4)|( 6<<0), //!<\n
      I2S3_CK_PC10         = (I2S3_CK             <<16)|( 2<<12)|(10<<4)|( 6<<0), //!<\n
      I2S3_MCK_PC7         = (I2S3_MCK            <<16)|( 2<<12)|( 7<<4)|( 6<<0), //!<\n
      I2S3_SD_PB2          = (I2S3_SD             <<16)|( 1<<12)|( 2<<4)|( 7<<0), //!<\n
      I2S3_SD_PB5          = (I2S3_SD             <<16)|( 1<<12)|( 5<<4)|( 6<<0), //!<\n
      I2S3_SD_PC12         = (I2S3_SD             <<16)|( 2<<12)|(12<<4)|( 6<<0), //!<\n
      I2S3_SD_PD6          = (I2S3_SD             <<16)|( 3<<12)|( 6<<4)|( 5<<0), //!<\n
      I2S3_WS_PA15         = (I2S3_WS             <<16)|( 0<<12)|(15<<4)|( 6<<0), //!<\n
      I2S3_WS_PA4          = (I2S3_WS             <<16)|( 0<<12)|( 4<<4)|( 6<<0), //!<\n
      I2S_CKIN_PC9         = (I2S_CKIN            <<16)|( 2<<12)|( 9<<4)|( 5<<0), //!<\n
      LPTIM1_ETR_PE0       = (LPTIM1_ETR          <<16)|( 4<<12)|( 0<<4)|( 3<<0), //!<\n
      LPTIM1_ETR_PG14      = (LPTIM1_ETR          <<16)|( 6<<12)|(14<<4)|( 3<<0), //!<\n
      LPTIM1_IN1_PD12      = (LPTIM1_IN1          <<16)|( 3<<12)|(12<<4)|( 3<<0), //!<\n
      LPTIM1_IN1_PG12      = (LPTIM1_IN1          <<16)|( 6<<12)|(12<<4)|( 3<<0), //!<\n
      LPTIM1_IN2_PE1       = (LPTIM1_IN2          <<16)|( 4<<12)|( 1<<4)|( 3<<0), //!<\n
      LPTIM1_IN2_PH2       = (LPTIM1_IN2          <<16)|( 7<<12)|( 2<<4)|( 3<<0), //!<\n
      LPTIM1_OUT_PD13      = (LPTIM1_OUT          <<16)|( 3<<12)|(13<<4)|( 3<<0), //!<\n
      LPTIM1_OUT_PG13      = (LPTIM1_OUT          <<16)|( 6<<12)|(13<<4)|( 3<<0), //!<\n
      LTDC_B0_PE4          = (LTDC_B0             <<16)|( 4<<12)|( 4<<4)|(14<<0), //!<\n
      LTDC_B0_PG14         = (LTDC_B0             <<16)|( 6<<12)|(14<<4)|(14<<0), //!<\n
      LTDC_B0_PJ12         = (LTDC_B0             <<16)|( 9<<12)|(12<<4)|(14<<0), //!<\n
      LTDC_B1_PA10         = (LTDC_B1             <<16)|( 0<<12)|(10<<4)|(14<<0), //!<\n
      LTDC_B1_PG12         = (LTDC_B1             <<16)|( 6<<12)|(12<<4)|(14<<0), //!<\n
      LTDC_B1_PJ13         = (LTDC_B1             <<16)|( 9<<12)|(13<<4)|(14<<0), //!<\n
      LTDC_B2_PA3          = (LTDC_B2             <<16)|( 0<<12)|( 3<<4)|( 9<<0), //!<\n
      LTDC_B2_PC9          = (LTDC_B2             <<16)|( 2<<12)|( 9<<4)|(14<<0), //!<\n
      LTDC_B2_PD6          = (LTDC_B2             <<16)|( 3<<12)|( 6<<4)|(14<<0), //!<\n
      LTDC_B2_PG10         = (LTDC_B2             <<16)|( 6<<12)|(10<<4)|(14<<0), //!<\n
      LTDC_B2_PJ14         = (LTDC_B2             <<16)|( 9<<12)|(14<<4)|(14<<0), //!<\n
      LTDC_B3_PA8          = (LTDC_B3             <<16)|( 0<<12)|( 8<<4)|(13<<0), //!<\n
      LTDC_B3_PD10         = (LTDC_B3             <<16)|( 3<<12)|(10<<4)|(14<<0), //!<\n
      LTDC_B3_PG11         = (LTDC_B3             <<16)|( 6<<12)|(11<<4)|(14<<0), //!<\n
      LTDC_B3_PJ15         = (LTDC_B3             <<16)|( 9<<12)|(15<<4)|(14<<0), //!<\n
      LTDC_B4_PA10         = (LTDC_B4             <<16)|( 0<<12)|(10<<4)|( 9<<0), //!<\n
      LTDC_B4_PE12         = (LTDC_B4             <<16)|( 4<<12)|(12<<4)|(14<<0), //!<\n
      LTDC_B4_PG12         = (LTDC_B4             <<16)|( 6<<12)|(12<<4)|( 9<<0), //!<\n
      LTDC_B4_PI4          = (LTDC_B4             <<16)|( 8<<12)|( 4<<4)|(14<<0), //!<\n
      LTDC_B4_PK3          = (LTDC_B4             <<16)|(10<<12)|( 3<<4)|(14<<0), //!<\n
      LTDC_B5_PA3          = (LTDC_B5             <<16)|( 0<<12)|( 3<<4)|(14<<0), //!<\n
      LTDC_B5_PI5          = (LTDC_B5             <<16)|( 8<<12)|( 5<<4)|(14<<0), //!<\n
      LTDC_B5_PK4          = (LTDC_B5             <<16)|(10<<12)|( 4<<4)|(14<<0), //!<\n
      LTDC_B6_PB8          = (LTDC_B6             <<16)|( 1<<12)|( 8<<4)|(14<<0), //!<\n
      LTDC_B6_PI6          = (LTDC_B6             <<16)|( 8<<12)|( 6<<4)|(14<<0), //!<\n
      LTDC_B6_PK5          = (LTDC_B6             <<16)|(10<<12)|( 5<<4)|(14<<0), //!<\n
      LTDC_B7_PB9          = (LTDC_B7             <<16)|( 1<<12)|( 9<<4)|(14<<0), //!<\n
      LTDC_B7_PI7          = (LTDC_B7             <<16)|( 8<<12)|( 7<<4)|(14<<0), //!<\n
      LTDC_B7_PK6          = (LTDC_B7             <<16)|(10<<12)|( 6<<4)|(14<<0), //!<\n
      LTDC_CLK_PE14        = (LTDC_CLK            <<16)|( 4<<12)|(14<<4)|(14<<0), //!<\n
      LTDC_CLK_PG7         = (LTDC_CLK            <<16)|( 6<<12)|( 7<<4)|(14<<0), //!<\n
      LTDC_CLK_PI14        = (LTDC_CLK            <<16)|( 8<<12)|(14<<4)|(14<<0), //!<\n
      LTDC_DE_PE13         = (LTDC_DE             <<16)|( 4<<12)|(13<<4)|(14<<0), //!<\n
      LTDC_DE_PF10         = (LTDC_DE             <<16)|( 5<<12)|(10<<4)|(14<<0), //!<\n
      LTDC_DE_PK7          = (LTDC_DE             <<16)|(10<<12)|( 7<<4)|(14<<0), //!<\n
      LTDC_G0_PB1          = (LTDC_G0             <<16)|( 1<<12)|( 1<<4)|(14<<0), //!<\n
      LTDC_G0_PE5          = (LTDC_G0             <<16)|( 4<<12)|( 5<<4)|(14<<0), //!<\n
      LTDC_G1_PB0          = (LTDC_G1             <<16)|( 1<<12)|( 0<<4)|(14<<0), //!<\n
      LTDC_G1_PE6          = (LTDC_G1             <<16)|( 4<<12)|( 6<<4)|(14<<0), //!<\n
      LTDC_G2_PA6          = (LTDC_G2             <<16)|( 0<<12)|( 6<<4)|(14<<0), //!<\n
      LTDC_G2_PH13         = (LTDC_G2             <<16)|( 7<<12)|(13<<4)|(14<<0), //!<\n
      LTDC_G2_PI15         = (LTDC_G2             <<16)|( 8<<12)|(15<<4)|( 9<<0), //!<\n
      LTDC_G3_PC9          = (LTDC_G3             <<16)|( 2<<12)|( 9<<4)|(10<<0), //!<\n
      LTDC_G3_PE11         = (LTDC_G3             <<16)|( 4<<12)|(11<<4)|(14<<0), //!<\n
      LTDC_G3_PG10         = (LTDC_G3             <<16)|( 6<<12)|(10<<4)|( 9<<0), //!<\n
      LTDC_G3_PH14         = (LTDC_G3             <<16)|( 7<<12)|(14<<4)|(14<<0), //!<\n
      LTDC_G3_PJ12         = (LTDC_G3             <<16)|( 9<<12)|(12<<4)|( 9<<0), //!<\n
      LTDC_G4_PB10         = (LTDC_G4             <<16)|( 1<<12)|(10<<4)|(14<<0), //!<\n
      LTDC_G4_PH15         = (LTDC_G4             <<16)|( 7<<12)|(15<<4)|(14<<0), //!<\n
      LTDC_G4_PH4          = (LTDC_G4             <<16)|( 7<<12)|( 4<<4)|(14<<0), //!<\n
      LTDC_G4_PJ13         = (LTDC_G4             <<16)|( 9<<12)|(13<<4)|( 9<<0), //!<\n
      LTDC_G5_PB11         = (LTDC_G5             <<16)|( 1<<12)|(11<<4)|(14<<0), //!<\n
      LTDC_G5_PH4          = (LTDC_G5             <<16)|( 7<<12)|( 4<<4)|( 9<<0), //!<\n
      LTDC_G5_PI0          = (LTDC_G5             <<16)|( 8<<12)|( 0<<4)|(14<<0), //!<\n
      LTDC_G6_PC7          = (LTDC_G6             <<16)|( 2<<12)|( 7<<4)|(14<<0), //!<\n
      LTDC_G6_PI1          = (LTDC_G6             <<16)|( 8<<12)|( 1<<4)|(14<<0), //!<\n
      LTDC_G6_PI11         = (LTDC_G6             <<16)|( 8<<12)|(11<<4)|( 9<<0), //!<\n
      LTDC_G7_PB5          = (LTDC_G7             <<16)|( 1<<12)|( 5<<4)|(14<<0), //!<\n
      LTDC_G7_PD3          = (LTDC_G7             <<16)|( 3<<12)|( 3<<4)|(14<<0), //!<\n
      LTDC_G7_PG8          = (LTDC_G7             <<16)|( 6<<12)|( 8<<4)|(14<<0), //!<\n
      LTDC_G7_PI2          = (LTDC_G7             <<16)|( 8<<12)|( 2<<4)|(14<<0), //!<\n
      LTDC_HSYNC_PC6       = (LTDC_HSYNC          <<16)|( 2<<12)|( 6<<4)|(14<<0), //!<\n
      LTDC_HSYNC_PI10      = (LTDC_HSYNC          <<16)|( 8<<12)|(10<<4)|(14<<0), //!<\n
      LTDC_HSYNC_PI12      = (LTDC_HSYNC          <<16)|( 8<<12)|(12<<4)|(14<<0), //!<\n
      LTDC_R0_PG13         = (LTDC_R0             <<16)|( 6<<12)|(13<<4)|(14<<0), //!<\n
      LTDC_R0_PH2          = (LTDC_R0             <<16)|( 7<<12)|( 2<<4)|(14<<0), //!<\n
      LTDC_R0_PI15         = (LTDC_R0             <<16)|( 8<<12)|(15<<4)|(14<<0), //!<\n
      LTDC_R1_PA2          = (LTDC_R1             <<16)|( 0<<12)|( 2<<4)|(14<<0), //!<\n
      LTDC_R1_PH3          = (LTDC_R1             <<16)|( 7<<12)|( 3<<4)|(14<<0), //!<\n
      LTDC_R1_PJ0          = (LTDC_R1             <<16)|( 9<<12)|( 0<<4)|(14<<0), //!<\n
      LTDC_R2_PA1          = (LTDC_R2             <<16)|( 0<<12)|( 1<<4)|(14<<0), //!<\n
      LTDC_R2_PC10         = (LTDC_R2             <<16)|( 2<<12)|(10<<4)|(14<<0), //!<\n
      LTDC_R2_PH8          = (LTDC_R2             <<16)|( 7<<12)|( 8<<4)|(14<<0), //!<\n
      LTDC_R2_PJ1          = (LTDC_R2             <<16)|( 9<<12)|( 1<<4)|(14<<0), //!<\n
      LTDC_R3_PB0          = (LTDC_R3             <<16)|( 1<<12)|( 0<<4)|( 9<<0), //!<\n
      LTDC_R3_PH9          = (LTDC_R3             <<16)|( 7<<12)|( 9<<4)|(14<<0), //!<\n
      LTDC_R3_PJ2          = (LTDC_R3             <<16)|( 9<<12)|( 2<<4)|(14<<0), //!<\n
      LTDC_R4_PA11         = (LTDC_R4             <<16)|( 0<<12)|(11<<4)|(14<<0), //!<\n
      LTDC_R4_PA5          = (LTDC_R4             <<16)|( 0<<12)|( 5<<4)|(14<<0), //!<\n
      LTDC_R4_PH10         = (LTDC_R4             <<16)|( 7<<12)|(10<<4)|(14<<0), //!<\n
      LTDC_R4_PJ3          = (LTDC_R4             <<16)|( 9<<12)|( 3<<4)|(14<<0), //!<\n
      LTDC_R5_PA12         = (LTDC_R5             <<16)|( 0<<12)|(12<<4)|(14<<0), //!<\n
      LTDC_R5_PA9          = (LTDC_R5             <<16)|( 0<<12)|( 9<<4)|(14<<0), //!<\n
      LTDC_R5_PC0          = (LTDC_R5             <<16)|( 2<<12)|( 0<<4)|(14<<0), //!<\n
      LTDC_R5_PH11         = (LTDC_R5             <<16)|( 7<<12)|(11<<4)|(14<<0), //!<\n
      LTDC_R5_PJ4          = (LTDC_R5             <<16)|( 9<<12)|( 4<<4)|(14<<0), //!<\n
      LTDC_R6_PA8          = (LTDC_R6             <<16)|( 0<<12)|( 8<<4)|(14<<0), //!<\n
      LTDC_R6_PB1          = (LTDC_R6             <<16)|( 1<<12)|( 1<<4)|( 9<<0), //!<\n
      LTDC_R6_PH12         = (LTDC_R6             <<16)|( 7<<12)|(12<<4)|(14<<0), //!<\n
      LTDC_R6_PJ5          = (LTDC_R6             <<16)|( 9<<12)|( 5<<4)|(14<<0), //!<\n
      LTDC_R7_PE15         = (LTDC_R7             <<16)|( 4<<12)|(15<<4)|(14<<0), //!<\n
      LTDC_R7_PG6          = (LTDC_R7             <<16)|( 6<<12)|( 6<<4)|(14<<0), //!<\n
      LTDC_R7_PJ0          = (LTDC_R7             <<16)|( 9<<12)|( 0<<4)|( 9<<0), //!<\n
      LTDC_VSYNC_PA4       = (LTDC_VSYNC          <<16)|( 0<<12)|( 4<<4)|(14<<0), //!<\n
      LTDC_VSYNC_PI13      = (LTDC_VSYNC          <<16)|( 8<<12)|(13<<4)|(14<<0), //!<\n
      LTDC_VSYNC_PI9       = (LTDC_VSYNC          <<16)|( 8<<12)|( 9<<4)|(14<<0), //!<\n
      MDIOS_MDC_PA6        = (MDIOS_MDC           <<16)|( 0<<12)|( 6<<4)|(12<<0), //!<\n
      MDIOS_MDC_PC1        = (MDIOS_MDC           <<16)|( 2<<12)|( 1<<4)|(12<<0), //!<\n
      MDIOS_MDIO_PA10      = (MDIOS_MDIO          <<16)|( 0<<12)|(10<<4)|(12<<0), //!<\n
      MDIOS_MDIO_PA2       = (MDIOS_MDIO          <<16)|( 0<<12)|( 2<<4)|(12<<0), //!<\n
      QUADSPI_BK1_IO0_PC9  = (QUADSPI_BK1_IO0     <<16)|( 2<<12)|( 9<<4)|( 9<<0), //!<\n
      QUADSPI_BK1_IO0_PD11 = (QUADSPI_BK1_IO0     <<16)|( 3<<12)|(11<<4)|( 9<<0), //!<\n
      QUADSPI_BK1_IO0_PF8  = (QUADSPI_BK1_IO0     <<16)|( 5<<12)|( 8<<4)|(10<<0), //!<\n
      QUADSPI_BK1_IO1_PC10 = (QUADSPI_BK1_IO1     <<16)|( 2<<12)|(10<<4)|( 9<<0), //!<\n
      QUADSPI_BK1_IO1_PD12 = (QUADSPI_BK1_IO1     <<16)|( 3<<12)|(12<<4)|( 9<<0), //!<\n
      QUADSPI_BK1_IO1_PF9  = (QUADSPI_BK1_IO1     <<16)|( 5<<12)|( 9<<4)|(10<<0), //!<\n
      QUADSPI_BK1_IO2_PE2  = (QUADSPI_BK1_IO2     <<16)|( 4<<12)|( 2<<4)|( 9<<0), //!<\n
      QUADSPI_BK1_IO2_PF7  = (QUADSPI_BK1_IO2     <<16)|( 5<<12)|( 7<<4)|( 9<<0), //!<\n
      QUADSPI_BK1_IO3_PA1  = (QUADSPI_BK1_IO3     <<16)|( 0<<12)|( 1<<4)|( 9<<0), //!<\n
      QUADSPI_BK1_IO3_PD13 = (QUADSPI_BK1_IO3     <<16)|( 3<<12)|(13<<4)|( 9<<0), //!<\n
      QUADSPI_BK1_IO3_PF6  = (QUADSPI_BK1_IO3     <<16)|( 5<<12)|( 6<<4)|( 9<<0), //!<\n
      QUADSPI_BK1_NCS_PB10 = (QUADSPI_BK1_NCS     <<16)|( 1<<12)|(10<<4)|( 9<<0), //!<\n
      QUADSPI_BK1_NCS_PB6  = (QUADSPI_BK1_NCS     <<16)|( 1<<12)|( 6<<4)|(10<<0), //!<\n
      QUADSPI_BK2_IO0_PE7  = (QUADSPI_BK2_IO0     <<16)|( 4<<12)|( 7<<4)|(10<<0), //!<\n
      QUADSPI_BK2_IO0_PH2  = (QUADSPI_BK2_IO0     <<16)|( 7<<12)|( 2<<4)|( 9<<0), //!<\n
      QUADSPI_BK2_IO1_PE8  = (QUADSPI_BK2_IO1     <<16)|( 4<<12)|( 8<<4)|(10<<0), //!<\n
      QUADSPI_BK2_IO1_PH3  = (QUADSPI_BK2_IO1     <<16)|( 7<<12)|( 3<<4)|( 9<<0), //!<\n
      QUADSPI_BK2_IO2_PE9  = (QUADSPI_BK2_IO2     <<16)|( 4<<12)|( 9<<4)|(10<<0), //!<\n
      QUADSPI_BK2_IO2_PG9  = (QUADSPI_BK2_IO2     <<16)|( 6<<12)|( 9<<4)|( 9<<0), //!<\n
      QUADSPI_BK2_IO3_PE10 = (QUADSPI_BK2_IO3     <<16)|( 4<<12)|(10<<4)|(10<<0), //!<\n
      QUADSPI_BK2_IO3_PG14 = (QUADSPI_BK2_IO3     <<16)|( 6<<12)|(14<<4)|( 9<<0), //!<\n
      QUADSPI_BK2_NCS_PC11 = (QUADSPI_BK2_NCS     <<16)|( 2<<12)|(11<<4)|( 9<<0), //!<\n
      QUADSPI_CLK_PB2      = (QUADSPI_CLK         <<16)|( 1<<12)|( 2<<4)|( 9<<0), //!<\n
      QUADSPI_CLK_PF10     = (QUADSPI_CLK         <<16)|( 5<<12)|(10<<4)|( 9<<0), //!<\n
      RCC_MCO_1_PA8        = (RCC_MCO_1           <<16)|( 0<<12)|( 8<<4)|( 0<<0), //!<\n
      RCC_MCO_2_PC9        = (RCC_MCO_2           <<16)|( 2<<12)|( 9<<4)|( 0<<0), //!<\n
      RTC_REFIN_PB15       = (RTC_REFIN           <<16)|( 1<<12)|(15<<4)|( 0<<0), //!<\n
      SAI1_FS_A_PE4        = (SAI1_FS_A           <<16)|( 4<<12)|( 4<<4)|( 6<<0), //!<\n
      SAI1_FS_B_PF9        = (SAI1_FS_B           <<16)|( 5<<12)|( 9<<4)|( 6<<0), //!<\n
      SAI1_MCLK_A_PE2      = (SAI1_MCLK_A         <<16)|( 4<<12)|( 2<<4)|( 6<<0), //!<\n
      SAI1_MCLK_A_PG7      = (SAI1_MCLK_A         <<16)|( 6<<12)|( 7<<4)|( 6<<0), //!<\n
      SAI1_MCLK_B_PF7      = (SAI1_MCLK_B         <<16)|( 5<<12)|( 7<<4)|( 6<<0), //!<\n
      SAI1_SCK_A_PE5       = (SAI1_SCK_A          <<16)|( 4<<12)|( 5<<4)|( 6<<0), //!<\n
      SAI1_SCK_B_PF8       = (SAI1_SCK_B          <<16)|( 5<<12)|( 8<<4)|( 6<<0), //!<\n
      SAI1_SD_A_PB2        = (SAI1_SD_A           <<16)|( 1<<12)|( 2<<4)|( 6<<0), //!<\n
      SAI1_SD_A_PC1        = (SAI1_SD_A           <<16)|( 2<<12)|( 1<<4)|( 6<<0), //!<\n
      SAI1_SD_A_PD6        = (SAI1_SD_A           <<16)|( 3<<12)|( 6<<4)|( 6<<0), //!<\n
      SAI1_SD_A_PE6        = (SAI1_SD_A           <<16)|( 4<<12)|( 6<<4)|( 6<<0), //!<\n
      SAI1_SD_B_PE3        = (SAI1_SD_B           <<16)|( 4<<12)|( 3<<4)|( 6<<0), //!<\n
      SAI1_SD_B_PF6        = (SAI1_SD_B           <<16)|( 5<<12)|( 6<<4)|( 6<<0), //!<\n
      SAI2_FS_A_PD12       = (SAI2_FS_A           <<16)|( 3<<12)|(12<<4)|(10<<0), //!<\n
      SAI2_FS_A_PI7        = (SAI2_FS_A           <<16)|( 8<<12)|( 7<<4)|(10<<0), //!<\n
      SAI2_FS_B_PA12       = (SAI2_FS_B           <<16)|( 0<<12)|(12<<4)|( 8<<0), //!<\n
      SAI2_FS_B_PC0        = (SAI2_FS_B           <<16)|( 2<<12)|( 0<<4)|( 8<<0), //!<\n
      SAI2_FS_B_PE13       = (SAI2_FS_B           <<16)|( 4<<12)|(13<<4)|(10<<0), //!<\n
      SAI2_FS_B_PG9        = (SAI2_FS_B           <<16)|( 6<<12)|( 9<<4)|(10<<0), //!<\n
      SAI2_MCLK_A_PE0      = (SAI2_MCLK_A         <<16)|( 4<<12)|( 0<<4)|(10<<0), //!<\n
      SAI2_MCLK_A_PI4      = (SAI2_MCLK_A         <<16)|( 8<<12)|( 4<<4)|(10<<0), //!<\n
      SAI2_MCLK_B_PA1      = (SAI2_MCLK_B         <<16)|( 0<<12)|( 1<<4)|(10<<0), //!<\n
      SAI2_MCLK_B_PE14     = (SAI2_MCLK_B         <<16)|( 4<<12)|(14<<4)|(10<<0), //!<\n
      SAI2_MCLK_B_PE6      = (SAI2_MCLK_B         <<16)|( 4<<12)|( 6<<4)|(10<<0), //!<\n
      SAI2_MCLK_B_PH3      = (SAI2_MCLK_B         <<16)|( 7<<12)|( 3<<4)|(10<<0), //!<\n
      SAI2_SCK_A_PD13      = (SAI2_SCK_A          <<16)|( 3<<12)|(13<<4)|(10<<0), //!<\n
      SAI2_SCK_A_PI5       = (SAI2_SCK_A          <<16)|( 8<<12)|( 5<<4)|(10<<0), //!<\n
      SAI2_SCK_B_PA2       = (SAI2_SCK_B          <<16)|( 0<<12)|( 2<<4)|( 8<<0), //!<\n
      SAI2_SCK_B_PE12      = (SAI2_SCK_B          <<16)|( 4<<12)|(12<<4)|(10<<0), //!<\n
      SAI2_SCK_B_PH2       = (SAI2_SCK_B          <<16)|( 7<<12)|( 2<<4)|(10<<0), //!<\n
      SAI2_SD_A_PD11       = (SAI2_SD_A           <<16)|( 3<<12)|(11<<4)|(10<<0), //!<\n
      SAI2_SD_A_PI6        = (SAI2_SD_A           <<16)|( 8<<12)|( 6<<4)|(10<<0), //!<\n
      SAI2_SD_B_PA0        = (SAI2_SD_B           <<16)|( 0<<12)|( 0<<4)|(10<<0), //!<\n
      SAI2_SD_B_PE11       = (SAI2_SD_B           <<16)|( 4<<12)|(11<<4)|(10<<0), //!<\n
      SAI2_SD_B_PF11       = (SAI2_SD_B           <<16)|( 5<<12)|(11<<4)|(10<<0), //!<\n
      SAI2_SD_B_PG10       = (SAI2_SD_B           <<16)|( 6<<12)|(10<<4)|(10<<0), //!<\n
      SDMMC1_CK_PC12       = (SDMMC1_CK           <<16)|( 2<<12)|(12<<4)|(12<<0), //!<\n
      SDMMC1_CMD_PD2       = (SDMMC1_CMD          <<16)|( 3<<12)|( 2<<4)|(12<<0), //!<\n
      SDMMC1_D0_PC8        = (SDMMC1_D0           <<16)|( 2<<12)|( 8<<4)|(12<<0), //!<\n
      SDMMC1_D1_PC9        = (SDMMC1_D1           <<16)|( 2<<12)|( 9<<4)|(12<<0), //!<\n
      SDMMC1_D2_PC10       = (SDMMC1_D2           <<16)|( 2<<12)|(10<<4)|(12<<0), //!<\n
      SDMMC1_D3_PC11       = (SDMMC1_D3           <<16)|( 2<<12)|(11<<4)|(12<<0), //!<\n
      SDMMC1_D4_PB8        = (SDMMC1_D4           <<16)|( 1<<12)|( 8<<4)|(12<<0), //!<\n
      SDMMC1_D5_PB9        = (SDMMC1_D5           <<16)|( 1<<12)|( 9<<4)|(12<<0), //!<\n
      SDMMC1_D6_PC6        = (SDMMC1_D6           <<16)|( 2<<12)|( 6<<4)|(12<<0), //!<\n
      SDMMC1_D7_PC7        = (SDMMC1_D7           <<16)|( 2<<12)|( 7<<4)|(12<<0), //!<\n
      SDMMC2_CK_PD6        = (SDMMC2_CK           <<16)|( 3<<12)|( 6<<4)|(11<<0), //!<\n
      SDMMC2_CMD_PD7       = (SDMMC2_CMD          <<16)|( 3<<12)|( 7<<4)|(11<<0), //!<\n
      SDMMC2_D0_PB14       = (SDMMC2_D0           <<16)|( 1<<12)|(14<<4)|(10<<0), //!<\n
      SDMMC2_D0_PG9        = (SDMMC2_D0           <<16)|( 6<<12)|( 9<<4)|(11<<0), //!<\n
      SDMMC2_D1_PB15       = (SDMMC2_D1           <<16)|( 1<<12)|(15<<4)|(10<<0), //!<\n
      SDMMC2_D1_PG10       = (SDMMC2_D1           <<16)|( 6<<12)|(10<<4)|(11<<0), //!<\n
      SDMMC2_D2_PB3        = (SDMMC2_D2           <<16)|( 1<<12)|( 3<<4)|(10<<0), //!<\n
      SDMMC2_D2_PG11       = (SDMMC2_D2           <<16)|( 6<<12)|(11<<4)|(10<<0), //!<\n
      SDMMC2_D3_PB4        = (SDMMC2_D3           <<16)|( 1<<12)|( 4<<4)|(10<<0), //!<\n
      SDMMC2_D3_PG12       = (SDMMC2_D3           <<16)|( 6<<12)|(12<<4)|(11<<0), //!<\n
      SDMMC2_D4_PB8        = (SDMMC2_D4           <<16)|( 1<<12)|( 8<<4)|(10<<0), //!<\n
      SDMMC2_D5_PB9        = (SDMMC2_D5           <<16)|( 1<<12)|( 9<<4)|(10<<0), //!<\n
      SDMMC2_D6_PC6        = (SDMMC2_D6           <<16)|( 2<<12)|( 6<<4)|(10<<0), //!<\n
      SDMMC2_D7_PC7        = (SDMMC2_D7           <<16)|( 2<<12)|( 7<<4)|(10<<0), //!<\n
      SPDIFRX_IN0_PD7      = (SPDIFRX_IN0         <<16)|( 3<<12)|( 7<<4)|( 8<<0), //!<\n
      SPDIFRX_IN0_PG11     = (SPDIFRX_IN0         <<16)|( 6<<12)|(11<<4)|( 7<<0), //!<\n
      SPDIFRX_IN1_PD8      = (SPDIFRX_IN1         <<16)|( 3<<12)|( 8<<4)|( 8<<0), //!<\n
      SPDIFRX_IN1_PG12     = (SPDIFRX_IN1         <<16)|( 6<<12)|(12<<4)|( 7<<0), //!<\n
      SPDIFRX_IN2_PC4      = (SPDIFRX_IN2         <<16)|( 2<<12)|( 4<<4)|( 8<<0), //!<\n
      SPDIFRX_IN2_PG8      = (SPDIFRX_IN2         <<16)|( 6<<12)|( 8<<4)|( 7<<0), //!<\n
      SPDIFRX_IN3_PC5      = (SPDIFRX_IN3         <<16)|( 2<<12)|( 5<<4)|( 8<<0), //!<\n
      SPDIFRX_IN3_PG9      = (SPDIFRX_IN3         <<16)|( 6<<12)|( 9<<4)|( 7<<0), //!<\n
      SPI1_MISO_PA6        = (SPI1_MISO           <<16)|( 0<<12)|( 6<<4)|( 5<<0), //!<\n
      SPI1_MISO_PB4        = (SPI1_MISO           <<16)|( 1<<12)|( 4<<4)|( 5<<0), //!<\n
      SPI1_MISO_PG9        = (SPI1_MISO           <<16)|( 6<<12)|( 9<<4)|( 5<<0), //!<\n
      SPI1_MOSI_PA7        = (SPI1_MOSI           <<16)|( 0<<12)|( 7<<4)|( 5<<0), //!<\n
      SPI1_MOSI_PB5        = (SPI1_MOSI           <<16)|( 1<<12)|( 5<<4)|( 5<<0), //!<\n
      SPI1_MOSI_PD7        = (SPI1_MOSI           <<16)|( 3<<12)|( 7<<4)|( 5<<0), //!<\n
      SPI1_NSS_PA15        = (SPI1_NSS            <<16)|( 0<<12)|(15<<4)|( 5<<0), //!<\n
      SPI1_NSS_PA4         = (SPI1_NSS            <<16)|( 0<<12)|( 4<<4)|( 5<<0), //!<\n
      SPI1_NSS_PG10        = (SPI1_NSS            <<16)|( 6<<12)|(10<<4)|( 5<<0), //!<\n
      SPI1_SCK_PA5         = (SPI1_SCK            <<16)|( 0<<12)|( 5<<4)|( 5<<0), //!<\n
      SPI1_SCK_PB3         = (SPI1_SCK            <<16)|( 1<<12)|( 3<<4)|( 5<<0), //!<\n
      SPI1_SCK_PG11        = (SPI1_SCK            <<16)|( 6<<12)|(11<<4)|( 5<<0), //!<\n
      SPI2_MISO_PB14       = (SPI2_MISO           <<16)|( 1<<12)|(14<<4)|( 5<<0), //!<\n
      SPI2_MISO_PC2        = (SPI2_MISO           <<16)|( 2<<12)|( 2<<4)|( 5<<0), //!<\n
      SPI2_MISO_PI2        = (SPI2_MISO           <<16)|( 8<<12)|( 2<<4)|( 5<<0), //!<\n
      SPI2_MOSI_PB15       = (SPI2_MOSI           <<16)|( 1<<12)|(15<<4)|( 5<<0), //!<\n
      SPI2_MOSI_PC1        = (SPI2_MOSI           <<16)|( 2<<12)|( 1<<4)|( 5<<0), //!<\n
      SPI2_MOSI_PC3        = (SPI2_MOSI           <<16)|( 2<<12)|( 3<<4)|( 5<<0), //!<\n
      SPI2_MOSI_PI3        = (SPI2_MOSI           <<16)|( 8<<12)|( 3<<4)|( 5<<0), //!<\n
      SPI2_NSS_PA11        = (SPI2_NSS            <<16)|( 0<<12)|(11<<4)|( 5<<0), //!<\n
      SPI2_NSS_PB12        = (SPI2_NSS            <<16)|( 1<<12)|(12<<4)|( 5<<0), //!<\n
      SPI2_NSS_PB4         = (SPI2_NSS            <<16)|( 1<<12)|( 4<<4)|( 7<<0), //!<\n
      SPI2_NSS_PB9         = (SPI2_NSS            <<16)|( 1<<12)|( 9<<4)|( 5<<0), //!<\n
      SPI2_NSS_PI0         = (SPI2_NSS            <<16)|( 8<<12)|( 0<<4)|( 5<<0), //!<\n
      SPI2_SCK_PA12        = (SPI2_SCK            <<16)|( 0<<12)|(12<<4)|( 5<<0), //!<\n
      SPI2_SCK_PA9         = (SPI2_SCK            <<16)|( 0<<12)|( 9<<4)|( 5<<0), //!<\n
      SPI2_SCK_PB10        = (SPI2_SCK            <<16)|( 1<<12)|(10<<4)|( 5<<0), //!<\n
      SPI2_SCK_PB13        = (SPI2_SCK            <<16)|( 1<<12)|(13<<4)|( 5<<0), //!<\n
      SPI2_SCK_PD3         = (SPI2_SCK            <<16)|( 3<<12)|( 3<<4)|( 5<<0), //!<\n
      SPI2_SCK_PI1         = (SPI2_SCK            <<16)|( 8<<12)|( 1<<4)|( 5<<0), //!<\n
      SPI3_MISO_PB4        = (SPI3_MISO           <<16)|( 1<<12)|( 4<<4)|( 6<<0), //!<\n
      SPI3_MISO_PC11       = (SPI3_MISO           <<16)|( 2<<12)|(11<<4)|( 6<<0), //!<\n
      SPI3_MOSI_PB2        = (SPI3_MOSI           <<16)|( 1<<12)|( 2<<4)|( 7<<0), //!<\n
      SPI3_MOSI_PB5        = (SPI3_MOSI           <<16)|( 1<<12)|( 5<<4)|( 6<<0), //!<\n
      SPI3_MOSI_PC12       = (SPI3_MOSI           <<16)|( 2<<12)|(12<<4)|( 6<<0), //!<\n
      SPI3_MOSI_PD6        = (SPI3_MOSI           <<16)|( 3<<12)|( 6<<4)|( 5<<0), //!<\n
      SPI3_NSS_PA15        = (SPI3_NSS            <<16)|( 0<<12)|(15<<4)|( 6<<0), //!<\n
      SPI3_NSS_PA4         = (SPI3_NSS            <<16)|( 0<<12)|( 4<<4)|( 6<<0), //!<\n
      SPI3_SCK_PB3         = (SPI3_SCK            <<16)|( 1<<12)|( 3<<4)|( 6<<0), //!<\n
      SPI3_SCK_PC10        = (SPI3_SCK            <<16)|( 2<<12)|(10<<4)|( 6<<0), //!<\n
      SPI4_MISO_PE13       = (SPI4_MISO           <<16)|( 4<<12)|(13<<4)|( 5<<0), //!<\n
      SPI4_MISO_PE5        = (SPI4_MISO           <<16)|( 4<<12)|( 5<<4)|( 5<<0), //!<\n
      SPI4_MOSI_PE14       = (SPI4_MOSI           <<16)|( 4<<12)|(14<<4)|( 5<<0), //!<\n
      SPI4_MOSI_PE6        = (SPI4_MOSI           <<16)|( 4<<12)|( 6<<4)|( 5<<0), //!<\n
      SPI4_NSS_PE11        = (SPI4_NSS            <<16)|( 4<<12)|(11<<4)|( 5<<0), //!<\n
      SPI4_NSS_PE4         = (SPI4_NSS            <<16)|( 4<<12)|( 4<<4)|( 5<<0), //!<\n
      SPI4_SCK_PE12        = (SPI4_SCK            <<16)|( 4<<12)|(12<<4)|( 5<<0), //!<\n
      SPI4_SCK_PE2         = (SPI4_SCK            <<16)|( 4<<12)|( 2<<4)|( 5<<0), //!<\n
      SPI5_MISO_PF8        = (SPI5_MISO           <<16)|( 5<<12)|( 8<<4)|( 5<<0), //!<\n
      SPI5_MISO_PH7        = (SPI5_MISO           <<16)|( 7<<12)|( 7<<4)|( 5<<0), //!<\n
      SPI5_MOSI_PF11       = (SPI5_MOSI           <<16)|( 5<<12)|(11<<4)|( 5<<0), //!<\n
      SPI5_MOSI_PF9        = (SPI5_MOSI           <<16)|( 5<<12)|( 9<<4)|( 5<<0), //!<\n
      SPI5_NSS_PF6         = (SPI5_NSS            <<16)|( 5<<12)|( 6<<4)|( 5<<0), //!<\n
      SPI5_NSS_PH5         = (SPI5_NSS            <<16)|( 7<<12)|( 5<<4)|( 5<<0), //!<\n
      SPI5_SCK_PF7         = (SPI5_SCK            <<16)|( 5<<12)|( 7<<4)|( 5<<0), //!<\n
      SPI5_SCK_PH6         = (SPI5_SCK            <<16)|( 7<<12)|( 6<<4)|( 5<<0), //!<\n
      SPI6_MISO_PA6        = (SPI6_MISO           <<16)|( 0<<12)|( 6<<4)|( 8<<0), //!<\n
      SPI6_MISO_PB4        = (SPI6_MISO           <<16)|( 1<<12)|( 4<<4)|( 8<<0), //!<\n
      SPI6_MISO_PG12       = (SPI6_MISO           <<16)|( 6<<12)|(12<<4)|( 5<<0), //!<\n
      SPI6_MOSI_PA7        = (SPI6_MOSI           <<16)|( 0<<12)|( 7<<4)|( 8<<0), //!<\n
      SPI6_MOSI_PB5        = (SPI6_MOSI           <<16)|( 1<<12)|( 5<<4)|( 8<<0), //!<\n
      SPI6_MOSI_PG14       = (SPI6_MOSI           <<16)|( 6<<12)|(14<<4)|( 5<<0), //!<\n
      SPI6_NSS_PA15        = (SPI6_NSS            <<16)|( 0<<12)|(15<<4)|( 7<<0), //!<\n
      SPI6_NSS_PA4         = (SPI6_NSS            <<16)|( 0<<12)|( 4<<4)|( 8<<0), //!<\n
      SPI6_NSS_PG8         = (SPI6_NSS            <<16)|( 6<<12)|( 8<<4)|( 5<<0), //!<\n
      SPI6_SCK_PA5         = (SPI6_SCK            <<16)|( 0<<12)|( 5<<4)|( 8<<0), //!<\n
      SPI6_SCK_PB3         = (SPI6_SCK            <<16)|( 1<<12)|( 3<<4)|( 8<<0), //!<\n
      SPI6_SCK_PG13        = (SPI6_SCK            <<16)|( 6<<12)|(13<<4)|( 5<<0), //!<\n
      SYS_JTCK_SWCLK_PA14  = (SYS_JTCK_SWCLK      <<16)|( 0<<12)|(14<<4)|( 0<<0), //!<\n
      SYS_JTDI_PA15        = (SYS_JTDI            <<16)|( 0<<12)|(15<<4)|( 0<<0), //!<\n
      SYS_JTDO_SWO_PB3     = (SYS_JTDO_SWO        <<16)|( 1<<12)|( 3<<4)|( 0<<0), //!<\n
      SYS_JTMS_SWDIO_PA13  = (SYS_JTMS_SWDIO      <<16)|( 0<<12)|(13<<4)|( 0<<0), //!<\n
      SYS_JTRST_PB4        = (SYS_JTRST           <<16)|( 1<<12)|( 4<<4)|( 0<<0), //!<\n
      SYS_TRACECLK_PE2     = (SYS_TRACECLK        <<16)|( 4<<12)|( 2<<4)|( 0<<0), //!<\n
      SYS_TRACED0_PC1      = (SYS_TRACED0         <<16)|( 2<<12)|( 1<<4)|( 0<<0), //!<\n
      SYS_TRACED0_PE3      = (SYS_TRACED0         <<16)|( 4<<12)|( 3<<4)|( 0<<0), //!<\n
      SYS_TRACED0_PG13     = (SYS_TRACED0         <<16)|( 6<<12)|(13<<4)|( 0<<0), //!<\n
      SYS_TRACED1_PC8      = (SYS_TRACED1         <<16)|( 2<<12)|( 8<<4)|( 0<<0), //!<\n
      SYS_TRACED1_PE4      = (SYS_TRACED1         <<16)|( 4<<12)|( 4<<4)|( 0<<0), //!<\n
      SYS_TRACED1_PG14     = (SYS_TRACED1         <<16)|( 6<<12)|(14<<4)|( 0<<0), //!<\n
      SYS_TRACED2_PD2      = (SYS_TRACED2         <<16)|( 3<<12)|( 2<<4)|( 0<<0), //!<\n
      SYS_TRACED2_PE5      = (SYS_TRACED2         <<16)|( 4<<12)|( 5<<4)|( 0<<0), //!<\n
      SYS_TRACED3_PC12     = (SYS_TRACED3         <<16)|( 2<<12)|(12<<4)|( 0<<0), //!<\n
      SYS_TRACED3_PE6      = (SYS_TRACED3         <<16)|( 4<<12)|( 6<<4)|( 0<<0), //!<\n
      TIM10_CH1_PB8        = (TIM10_CH1           <<16)|( 1<<12)|( 8<<4)|( 3<<0), //!<\n
      TIM10_CH1_PF6        = (TIM10_CH1           <<16)|( 5<<12)|( 6<<4)|( 3<<0), //!<\n
      TIM11_CH1_PB9        = (TIM11_CH1           <<16)|( 1<<12)|( 9<<4)|( 3<<0), //!<\n
      TIM11_CH1_PF7        = (TIM11_CH1           <<16)|( 5<<12)|( 7<<4)|( 3<<0), //!<\n
      TIM12_CH1_PB14       = (TIM12_CH1           <<16)|( 1<<12)|(14<<4)|( 9<<0), //!<\n
      TIM12_CH1_PH6        = (TIM12_CH1           <<16)|( 7<<12)|( 6<<4)|( 9<<0), //!<\n
      TIM12_CH2_PB15       = (TIM12_CH2           <<16)|( 1<<12)|(15<<4)|( 9<<0), //!<\n
      TIM12_CH2_PH9        = (TIM12_CH2           <<16)|( 7<<12)|( 9<<4)|( 9<<0), //!<\n
      TIM13_CH1_PA6        = (TIM13_CH1           <<16)|( 0<<12)|( 6<<4)|( 9<<0), //!<\n
      TIM13_CH1_PF8        = (TIM13_CH1           <<16)|( 5<<12)|( 8<<4)|( 9<<0), //!<\n
      TIM14_CH1_PA7        = (TIM14_CH1           <<16)|( 0<<12)|( 7<<4)|( 9<<0), //!<\n
      TIM14_CH1_PF9        = (TIM14_CH1           <<16)|( 5<<12)|( 9<<4)|( 9<<0), //!<\n
      TIM1_BKIN_PA6        = (TIM1_BKIN           <<16)|( 0<<12)|( 6<<4)|( 1<<0), //!<\n
      TIM1_BKIN_PB12       = (TIM1_BKIN           <<16)|( 1<<12)|(12<<4)|( 1<<0), //!<\n
      TIM1_BKIN_PE15       = (TIM1_BKIN           <<16)|( 4<<12)|(15<<4)|( 1<<0), //!<\n
      TIM1_BKIN2_PE6       = (TIM1_BKIN2          <<16)|( 4<<12)|( 6<<4)|( 1<<0), //!<\n
      TIM1_CH1_PA8         = (TIM1_CH1            <<16)|( 0<<12)|( 8<<4)|( 1<<0), //!<\n
      TIM1_CH1_PE9         = (TIM1_CH1            <<16)|( 4<<12)|( 9<<4)|( 1<<0), //!<\n
      TIM1_CH1N_PA7        = (TIM1_CH1N           <<16)|( 0<<12)|( 7<<4)|( 1<<0), //!<\n
      TIM1_CH1N_PB13       = (TIM1_CH1N           <<16)|( 1<<12)|(13<<4)|( 1<<0), //!<\n
      TIM1_CH1N_PE8        = (TIM1_CH1N           <<16)|( 4<<12)|( 8<<4)|( 1<<0), //!<\n
      TIM1_CH2_PA9         = (TIM1_CH2            <<16)|( 0<<12)|( 9<<4)|( 1<<0), //!<\n
      TIM1_CH2_PE11        = (TIM1_CH2            <<16)|( 4<<12)|(11<<4)|( 1<<0), //!<\n
      TIM1_CH2N_PB0        = (TIM1_CH2N           <<16)|( 1<<12)|( 0<<4)|( 1<<0), //!<\n
      TIM1_CH2N_PB14       = (TIM1_CH2N           <<16)|( 1<<12)|(14<<4)|( 1<<0), //!<\n
      TIM1_CH2N_PE10       = (TIM1_CH2N           <<16)|( 4<<12)|(10<<4)|( 1<<0), //!<\n
      TIM1_CH3_PA10        = (TIM1_CH3            <<16)|( 0<<12)|(10<<4)|( 1<<0), //!<\n
      TIM1_CH3_PE13        = (TIM1_CH3            <<16)|( 4<<12)|(13<<4)|( 1<<0), //!<\n
      TIM1_CH3N_PB1        = (TIM1_CH3N           <<16)|( 1<<12)|( 1<<4)|( 1<<0), //!<\n
      TIM1_CH3N_PB15       = (TIM1_CH3N           <<16)|( 1<<12)|(15<<4)|( 1<<0), //!<\n
      TIM1_CH3N_PE12       = (TIM1_CH3N           <<16)|( 4<<12)|(12<<4)|( 1<<0), //!<\n
      TIM1_CH4_PA11        = (TIM1_CH4            <<16)|( 0<<12)|(11<<4)|( 1<<0), //!<\n
      TIM1_CH4_PE14        = (TIM1_CH4            <<16)|( 4<<12)|(14<<4)|( 1<<0), //!<\n
      TIM1_ETR_PA12        = (TIM1_ETR            <<16)|( 0<<12)|(12<<4)|( 1<<0), //!<\n
      TIM1_ETR_PE7         = (TIM1_ETR            <<16)|( 4<<12)|( 7<<4)|( 1<<0), //!<\n
      TIM2_CH1_PA0         = (TIM2_CH1            <<16)|( 0<<12)|( 0<<4)|( 1<<0), //!<\n
      TIM2_CH1_PA15        = (TIM2_CH1            <<16)|( 0<<12)|(15<<4)|( 1<<0), //!<\n
      TIM2_CH1_PA5         = (TIM2_CH1            <<16)|( 0<<12)|( 5<<4)|( 1<<0), //!<\n
      TIM2_CH2_PA1         = (TIM2_CH2            <<16)|( 0<<12)|( 1<<4)|( 1<<0), //!<\n
      TIM2_CH2_PB3         = (TIM2_CH2            <<16)|( 1<<12)|( 3<<4)|( 1<<0), //!<\n
      TIM2_CH3_PA2         = (TIM2_CH3            <<16)|( 0<<12)|( 2<<4)|( 1<<0), //!<\n
      TIM2_CH3_PB10        = (TIM2_CH3            <<16)|( 1<<12)|(10<<4)|( 1<<0), //!<\n
      TIM2_CH4_PA3         = (TIM2_CH4            <<16)|( 0<<12)|( 3<<4)|( 1<<0), //!<\n
      TIM2_CH4_PB11        = (TIM2_CH4            <<16)|( 1<<12)|(11<<4)|( 1<<0), //!<\n
      TIM2_ETR_PA0         = (TIM2_ETR            <<16)|( 0<<12)|( 0<<4)|( 1<<0), //!<\n
      TIM2_ETR_PA15        = (TIM2_ETR            <<16)|( 0<<12)|(15<<4)|( 1<<0), //!<\n
      TIM2_ETR_PA5         = (TIM2_ETR            <<16)|( 0<<12)|( 5<<4)|( 1<<0), //!<\n
      TIM3_CH1_PA6         = (TIM3_CH1            <<16)|( 0<<12)|( 6<<4)|( 2<<0), //!<\n
      TIM3_CH1_PB4         = (TIM3_CH1            <<16)|( 1<<12)|( 4<<4)|( 2<<0), //!<\n
      TIM3_CH1_PC6         = (TIM3_CH1            <<16)|( 2<<12)|( 6<<4)|( 2<<0), //!<\n
      TIM3_CH2_PA7         = (TIM3_CH2            <<16)|( 0<<12)|( 7<<4)|( 2<<0), //!<\n
      TIM3_CH2_PB5         = (TIM3_CH2            <<16)|( 1<<12)|( 5<<4)|( 2<<0), //!<\n
      TIM3_CH2_PC7         = (TIM3_CH2            <<16)|( 2<<12)|( 7<<4)|( 2<<0), //!<\n
      TIM3_CH3_PB0         = (TIM3_CH3            <<16)|( 1<<12)|( 0<<4)|( 2<<0), //!<\n
      TIM3_CH3_PC8         = (TIM3_CH3            <<16)|( 2<<12)|( 8<<4)|( 2<<0), //!<\n
      TIM3_CH4_PB1         = (TIM3_CH4            <<16)|( 1<<12)|( 1<<4)|( 2<<0), //!<\n
      TIM3_CH4_PC9         = (TIM3_CH4            <<16)|( 2<<12)|( 9<<4)|( 2<<0), //!<\n
      TIM3_ETR_PD2         = (TIM3_ETR            <<16)|( 3<<12)|( 2<<4)|( 2<<0), //!<\n
      TIM4_CH1_PB6         = (TIM4_CH1            <<16)|( 1<<12)|( 6<<4)|( 2<<0), //!<\n
      TIM4_CH1_PD12        = (TIM4_CH1            <<16)|( 3<<12)|(12<<4)|( 2<<0), //!<\n
      TIM4_CH2_PB7         = (TIM4_CH2            <<16)|( 1<<12)|( 7<<4)|( 2<<0), //!<\n
      TIM4_CH2_PD13        = (TIM4_CH2            <<16)|( 3<<12)|(13<<4)|( 2<<0), //!<\n
      TIM4_CH3_PB8         = (TIM4_CH3            <<16)|( 1<<12)|( 8<<4)|( 2<<0), //!<\n
      TIM4_CH3_PD14        = (TIM4_CH3            <<16)|( 3<<12)|(14<<4)|( 2<<0), //!<\n
      TIM4_CH4_PB9         = (TIM4_CH4            <<16)|( 1<<12)|( 9<<4)|( 2<<0), //!<\n
      TIM4_CH4_PD15        = (TIM4_CH4            <<16)|( 3<<12)|(15<<4)|( 2<<0), //!<\n
      TIM4_ETR_PE0         = (TIM4_ETR            <<16)|( 4<<12)|( 0<<4)|( 2<<0), //!<\n
      TIM5_CH1_PA0         = (TIM5_CH1            <<16)|( 0<<12)|( 0<<4)|( 2<<0), //!<\n
      TIM5_CH1_PH10        = (TIM5_CH1            <<16)|( 7<<12)|(10<<4)|( 2<<0), //!<\n
      TIM5_CH2_PA1         = (TIM5_CH2            <<16)|( 0<<12)|( 1<<4)|( 2<<0), //!<\n
      TIM5_CH2_PH11        = (TIM5_CH2            <<16)|( 7<<12)|(11<<4)|( 2<<0), //!<\n
      TIM5_CH3_PA2         = (TIM5_CH3            <<16)|( 0<<12)|( 2<<4)|( 2<<0), //!<\n
      TIM5_CH3_PH12        = (TIM5_CH3            <<16)|( 7<<12)|(12<<4)|( 2<<0), //!<\n
      TIM5_CH4_PA3         = (TIM5_CH4            <<16)|( 0<<12)|( 3<<4)|( 2<<0), //!<\n
      TIM5_CH4_PI0         = (TIM5_CH4            <<16)|( 8<<12)|( 0<<4)|( 2<<0), //!<\n
      TIM8_BKIN_PA6        = (TIM8_BKIN           <<16)|( 0<<12)|( 6<<4)|( 3<<0), //!<\n
      TIM8_BKIN_PI4        = (TIM8_BKIN           <<16)|( 8<<12)|( 4<<4)|( 3<<0), //!<\n
      TIM8_BKIN2_PA8       = (TIM8_BKIN2          <<16)|( 0<<12)|( 8<<4)|( 3<<0), //!<\n
      TIM8_BKIN2_PI1       = (TIM8_BKIN2          <<16)|( 8<<12)|( 1<<4)|( 3<<0), //!<\n
      TIM8_CH1_PC6         = (TIM8_CH1            <<16)|( 2<<12)|( 6<<4)|( 3<<0), //!<\n
      TIM8_CH1_PI5         = (TIM8_CH1            <<16)|( 8<<12)|( 5<<4)|( 3<<0), //!<\n
      TIM8_CH1N_PA5        = (TIM8_CH1N           <<16)|( 0<<12)|( 5<<4)|( 3<<0), //!<\n
      TIM8_CH1N_PA7        = (TIM8_CH1N           <<16)|( 0<<12)|( 7<<4)|( 3<<0), //!<\n
      TIM8_CH1N_PH13       = (TIM8_CH1N           <<16)|( 7<<12)|(13<<4)|( 3<<0), //!<\n
      TIM8_CH2_PC7         = (TIM8_CH2            <<16)|( 2<<12)|( 7<<4)|( 3<<0), //!<\n
      TIM8_CH2_PI6         = (TIM8_CH2            <<16)|( 8<<12)|( 6<<4)|( 3<<0), //!<\n
      TIM8_CH2N_PB0        = (TIM8_CH2N           <<16)|( 1<<12)|( 0<<4)|( 3<<0), //!<\n
      TIM8_CH2N_PB14       = (TIM8_CH2N           <<16)|( 1<<12)|(14<<4)|( 3<<0), //!<\n
      TIM8_CH2N_PH14       = (TIM8_CH2N           <<16)|( 7<<12)|(14<<4)|( 3<<0), //!<\n
      TIM8_CH3_PC8         = (TIM8_CH3            <<16)|( 2<<12)|( 8<<4)|( 3<<0), //!<\n
      TIM8_CH3_PI7         = (TIM8_CH3            <<16)|( 8<<12)|( 7<<4)|( 3<<0), //!<\n
      TIM8_CH3N_PB1        = (TIM8_CH3N           <<16)|( 1<<12)|( 1<<4)|( 3<<0), //!<\n
      TIM8_CH3N_PB15       = (TIM8_CH3N           <<16)|( 1<<12)|(15<<4)|( 3<<0), //!<\n
      TIM8_CH3N_PH15       = (TIM8_CH3N           <<16)|( 7<<12)|(15<<4)|( 3<<0), //!<\n
      TIM8_CH4_PC9         = (TIM8_CH4            <<16)|( 2<<12)|( 9<<4)|( 3<<0), //!<\n
      TIM8_CH4_PI2         = (TIM8_CH4            <<16)|( 8<<12)|( 2<<4)|( 3<<0), //!<\n
      TIM8_ETR_PA0         = (TIM8_ETR            <<16)|( 0<<12)|( 0<<4)|( 3<<0), //!<\n
      TIM8_ETR_PI3         = (TIM8_ETR            <<16)|( 8<<12)|( 3<<4)|( 3<<0), //!<\n
      TIM9_CH1_PA2         = (TIM9_CH1            <<16)|( 0<<12)|( 2<<4)|( 3<<0), //!<\n
      TIM9_CH1_PE5         = (TIM9_CH1            <<16)|( 4<<12)|( 5<<4)|( 3<<0), //!<\n
      TIM9_CH2_PA3         = (TIM9_CH2            <<16)|( 0<<12)|( 3<<4)|( 3<<0), //!<\n
      TIM9_CH2_PE6         = (TIM9_CH2            <<16)|( 4<<12)|( 6<<4)|( 3<<0), //!<\n
      UART4_CTS_PB0        = (UART4_CTS           <<16)|( 1<<12)|( 0<<4)|( 8<<0), //!<\n
      UART4_CTS_PB15       = (UART4_CTS           <<16)|( 1<<12)|(15<<4)|( 8<<0), //!<\n
      UART4_DE_PA15        = (UART4_DE            <<16)|( 0<<12)|(15<<4)|( 8<<0), //!<\n
      UART4_DE_PB14        = (UART4_DE            <<16)|( 1<<12)|(14<<4)|( 8<<0), //!<\n
      UART4_RTS_PA15       = (UART4_RTS           <<16)|( 0<<12)|(15<<4)|( 8<<0), //!<\n
      UART4_RTS_PB14       = (UART4_RTS           <<16)|( 1<<12)|(14<<4)|( 8<<0), //!<\n
      UART4_RX_PA1         = (UART4_RX            <<16)|( 0<<12)|( 1<<4)|( 8<<0), //!<\n
      UART4_RX_PA11        = (UART4_RX            <<16)|( 0<<12)|(11<<4)|( 6<<0), //!<\n
      UART4_RX_PC11        = (UART4_RX            <<16)|( 2<<12)|(11<<4)|( 8<<0), //!<\n
      UART4_RX_PD0         = (UART4_RX            <<16)|( 3<<12)|( 0<<4)|( 8<<0), //!<\n
      UART4_RX_PH14        = (UART4_RX            <<16)|( 7<<12)|(14<<4)|( 8<<0), //!<\n
      UART4_RX_PI9         = (UART4_RX            <<16)|( 8<<12)|( 9<<4)|( 8<<0), //!<\n
      UART4_TX_PA0         = (UART4_TX            <<16)|( 0<<12)|( 0<<4)|( 8<<0), //!<\n
      UART4_TX_PA12        = (UART4_TX            <<16)|( 0<<12)|(12<<4)|( 6<<0), //!<\n
      UART4_TX_PC10        = (UART4_TX            <<16)|( 2<<12)|(10<<4)|( 8<<0), //!<\n
      UART4_TX_PD1         = (UART4_TX            <<16)|( 3<<12)|( 1<<4)|( 8<<0), //!<\n
      UART4_TX_PH13        = (UART4_TX            <<16)|( 7<<12)|(13<<4)|( 8<<0), //!<\n
      UART5_CTS_PC9        = (UART5_CTS           <<16)|( 2<<12)|( 9<<4)|( 7<<0), //!<\n
      UART5_DE_PC8         = (UART5_DE            <<16)|( 2<<12)|( 8<<4)|( 7<<0), //!<\n
      UART5_RTS_PC8        = (UART5_RTS           <<16)|( 2<<12)|( 8<<4)|( 7<<0), //!<\n
      UART5_RX_PB12        = (UART5_RX            <<16)|( 1<<12)|(12<<4)|( 8<<0), //!<\n
      UART5_RX_PB5         = (UART5_RX            <<16)|( 1<<12)|( 5<<4)|( 1<<0), //!<\n
      UART5_RX_PB8         = (UART5_RX            <<16)|( 1<<12)|( 8<<4)|( 7<<0), //!<\n
      UART5_RX_PD2         = (UART5_RX            <<16)|( 3<<12)|( 2<<4)|( 8<<0), //!<\n
      UART5_TX_PB13        = (UART5_TX            <<16)|( 1<<12)|(13<<4)|( 8<<0), //!<\n
      UART5_TX_PB6         = (UART5_TX            <<16)|( 1<<12)|( 6<<4)|( 1<<0), //!<\n
      UART5_TX_PB9         = (UART5_TX            <<16)|( 1<<12)|( 9<<4)|( 7<<0), //!<\n
      UART5_TX_PC12        = (UART5_TX            <<16)|( 2<<12)|(12<<4)|( 8<<0), //!<\n
      UART7_CTS_PE10       = (UART7_CTS           <<16)|( 4<<12)|(10<<4)|( 8<<0), //!<\n
      UART7_CTS_PF9        = (UART7_CTS           <<16)|( 5<<12)|( 9<<4)|( 8<<0), //!<\n
      UART7_DE_PE9         = (UART7_DE            <<16)|( 4<<12)|( 9<<4)|( 8<<0), //!<\n
      UART7_DE_PF8         = (UART7_DE            <<16)|( 5<<12)|( 8<<4)|( 8<<0), //!<\n
      UART7_RTS_PE9        = (UART7_RTS           <<16)|( 4<<12)|( 9<<4)|( 8<<0), //!<\n
      UART7_RTS_PF8        = (UART7_RTS           <<16)|( 5<<12)|( 8<<4)|( 8<<0), //!<\n
      UART7_RX_PA8         = (UART7_RX            <<16)|( 0<<12)|( 8<<4)|(12<<0), //!<\n
      UART7_RX_PB3         = (UART7_RX            <<16)|( 1<<12)|( 3<<4)|(12<<0), //!<\n
      UART7_RX_PE7         = (UART7_RX            <<16)|( 4<<12)|( 7<<4)|( 8<<0), //!<\n
      UART7_RX_PF6         = (UART7_RX            <<16)|( 5<<12)|( 6<<4)|( 8<<0), //!<\n
      UART7_TX_PA15        = (UART7_TX            <<16)|( 0<<12)|(15<<4)|(12<<0), //!<\n
      UART7_TX_PB4         = (UART7_TX            <<16)|( 1<<12)|( 4<<4)|(12<<0), //!<\n
      UART7_TX_PE8         = (UART7_TX            <<16)|( 4<<12)|( 8<<4)|( 8<<0), //!<\n
      UART7_TX_PF7         = (UART7_TX            <<16)|( 5<<12)|( 7<<4)|( 8<<0), //!<\n
      UART8_CTS_PD14       = (UART8_CTS           <<16)|( 3<<12)|(14<<4)|( 8<<0), //!<\n
      UART8_DE_PD15        = (UART8_DE            <<16)|( 3<<12)|(15<<4)|( 8<<0), //!<\n
      UART8_RTS_PD15       = (UART8_RTS           <<16)|( 3<<12)|(15<<4)|( 8<<0), //!<\n
      UART8_RX_PE0         = (UART8_RX            <<16)|( 4<<12)|( 0<<4)|( 8<<0), //!<\n
      UART8_TX_PE1         = (UART8_TX            <<16)|( 4<<12)|( 1<<4)|( 8<<0), //!<\n
      USART1_CK_PA8        = (USART1_CK           <<16)|( 0<<12)|( 8<<4)|( 7<<0), //!<\n
      USART1_CTS_PA11      = (USART1_CTS          <<16)|( 0<<12)|(11<<4)|( 7<<0), //!<\n
      USART1_DE_PA12       = (USART1_DE           <<16)|( 0<<12)|(12<<4)|( 7<<0), //!<\n
      USART1_RTS_PA12      = (USART1_RTS          <<16)|( 0<<12)|(12<<4)|( 7<<0), //!<\n
      USART1_RX_PA10       = (USART1_RX           <<16)|( 0<<12)|(10<<4)|( 7<<0), //!<\n
      USART1_RX_PB15       = (USART1_RX           <<16)|( 1<<12)|(15<<4)|( 4<<0), //!<\n
      USART1_RX_PB7        = (USART1_RX           <<16)|( 1<<12)|( 7<<4)|( 7<<0), //!<\n
      USART1_TX_PA9        = (USART1_TX           <<16)|( 0<<12)|( 9<<4)|( 7<<0), //!<\n
      USART1_TX_PB14       = (USART1_TX           <<16)|( 1<<12)|(14<<4)|( 4<<0), //!<\n
      USART1_TX_PB6        = (USART1_TX           <<16)|( 1<<12)|( 6<<4)|( 7<<0), //!<\n
      USART2_CK_PA4        = (USART2_CK           <<16)|( 0<<12)|( 4<<4)|( 7<<0), //!<\n
      USART2_CK_PD7        = (USART2_CK           <<16)|( 3<<12)|( 7<<4)|( 7<<0), //!<\n
      USART2_CTS_PA0       = (USART2_CTS          <<16)|( 0<<12)|( 0<<4)|( 7<<0), //!<\n
      USART2_CTS_PD3       = (USART2_CTS          <<16)|( 3<<12)|( 3<<4)|( 7<<0), //!<\n
      USART2_DE_PA1        = (USART2_DE           <<16)|( 0<<12)|( 1<<4)|( 7<<0), //!<\n
      USART2_DE_PD4        = (USART2_DE           <<16)|( 3<<12)|( 4<<4)|( 7<<0), //!<\n
      USART2_RTS_PA1       = (USART2_RTS          <<16)|( 0<<12)|( 1<<4)|( 7<<0), //!<\n
      USART2_RTS_PD4       = (USART2_RTS          <<16)|( 3<<12)|( 4<<4)|( 7<<0), //!<\n
      USART2_RX_PA3        = (USART2_RX           <<16)|( 0<<12)|( 3<<4)|( 7<<0), //!<\n
      USART2_RX_PD6        = (USART2_RX           <<16)|( 3<<12)|( 6<<4)|( 7<<0), //!<\n
      USART2_TX_PA2        = (USART2_TX           <<16)|( 0<<12)|( 2<<4)|( 7<<0), //!<\n
      USART2_TX_PD5        = (USART2_TX           <<16)|( 3<<12)|( 5<<4)|( 7<<0), //!<\n
      USART3_CK_PB12       = (USART3_CK           <<16)|( 1<<12)|(12<<4)|( 7<<0), //!<\n
      USART3_CK_PC12       = (USART3_CK           <<16)|( 2<<12)|(12<<4)|( 7<<0), //!<\n
      USART3_CK_PD10       = (USART3_CK           <<16)|( 3<<12)|(10<<4)|( 7<<0), //!<\n
      USART3_CTS_PB13      = (USART3_CTS          <<16)|( 1<<12)|(13<<4)|( 7<<0), //!<\n
      USART3_CTS_PD11      = (USART3_CTS          <<16)|( 3<<12)|(11<<4)|( 7<<0), //!<\n
      USART3_DE_PB14       = (USART3_DE           <<16)|( 1<<12)|(14<<4)|( 7<<0), //!<\n
      USART3_DE_PD12       = (USART3_DE           <<16)|( 3<<12)|(12<<4)|( 7<<0), //!<\n
      USART3_RTS_PB14      = (USART3_RTS          <<16)|( 1<<12)|(14<<4)|( 7<<0), //!<\n
      USART3_RTS_PD12      = (USART3_RTS          <<16)|( 3<<12)|(12<<4)|( 7<<0), //!<\n
      USART3_RX_PB11       = (USART3_RX           <<16)|( 1<<12)|(11<<4)|( 7<<0), //!<\n
      USART3_RX_PC11       = (USART3_RX           <<16)|( 2<<12)|(11<<4)|( 7<<0), //!<\n
      USART3_RX_PD9        = (USART3_RX           <<16)|( 3<<12)|( 9<<4)|( 7<<0), //!<\n
      USART3_TX_PB10       = (USART3_TX           <<16)|( 1<<12)|(10<<4)|( 7<<0), //!<\n
      USART3_TX_PC10       = (USART3_TX           <<16)|( 2<<12)|(10<<4)|( 7<<0), //!<\n
      USART3_TX_PD8        = (USART3_TX           <<16)|( 3<<12)|( 8<<4)|( 7<<0), //!<\n
      USART6_CK_PC8        = (USART6_CK           <<16)|( 2<<12)|( 8<<4)|( 8<<0), //!<\n
      USART6_CK_PG7        = (USART6_CK           <<16)|( 6<<12)|( 7<<4)|( 8<<0), //!<\n
      USART6_CTS_PG13      = (USART6_CTS          <<16)|( 6<<12)|(13<<4)|( 8<<0), //!<\n
      USART6_CTS_PG15      = (USART6_CTS          <<16)|( 6<<12)|(15<<4)|( 8<<0), //!<\n
      USART6_DE_PG12       = (USART6_DE           <<16)|( 6<<12)|(12<<4)|( 8<<0), //!<\n
      USART6_DE_PG8        = (USART6_DE           <<16)|( 6<<12)|( 8<<4)|( 8<<0), //!<\n
      USART6_RTS_PG12      = (USART6_RTS          <<16)|( 6<<12)|(12<<4)|( 8<<0), //!<\n
      USART6_RTS_PG8       = (USART6_RTS          <<16)|( 6<<12)|( 8<<4)|( 8<<0), //!<\n
      USART6_RX_PC7        = (USART6_RX           <<16)|( 2<<12)|( 7<<4)|( 8<<0), //!<\n
      USART6_RX_PG9        = (USART6_RX           <<16)|( 6<<12)|( 9<<4)|( 8<<0), //!<\n
      USART6_TX_PC6        = (USART6_TX           <<16)|( 2<<12)|( 6<<4)|( 8<<0), //!<\n
      USART6_TX_PG14       = (USART6_TX           <<16)|( 6<<12)|(14<<4)|( 8<<0), //!<\n
      USB_OTG_FS_DM_PA11   = (USB_OTG_FS_DM       <<16)|( 0<<12)|(11<<4)|(10<<0), //!<\n
      USB_OTG_FS_DP_PA12   = (USB_OTG_FS_DP       <<16)|( 0<<12)|(12<<4)|(10<<0), //!<\n
      USB_OTG_FS_ID_PA10   = (USB_OTG_FS_ID       <<16)|( 0<<12)|(10<<4)|(10<<0), //!<\n
      USB_OTG_FS_SOF_PA8   = (USB_OTG_FS_SOF      <<16)|( 0<<12)|( 8<<4)|(10<<0), //!<\n
      USB_OTG_HS_DM_PB14   = (USB_OTG_HS_DM       <<16)|( 1<<12)|(14<<4)|(12<<0), //!<\n
      USB_OTG_HS_DP_PB15   = (USB_OTG_HS_DP       <<16)|( 1<<12)|(15<<4)|(12<<0), //!<\n
      USB_OTG_HS_ID_PB12   = (USB_OTG_HS_ID       <<16)|( 1<<12)|(12<<4)|(12<<0), //!<\n
      USB_OTG_HS_SOF_PA4   = (USB_OTG_HS_SOF      <<16)|( 0<<12)|( 4<<4)|(12<<0), //!<\n
      USB_OTG_HS_ULPI_CK_PA5 = (USB_OTG_HS_ULPI_CK  <<16)|( 0<<12)|( 5<<4)|(10<<0), //!<\n
      USB_OTG_HS_ULPI_D0_PA3 = (USB_OTG_HS_ULPI_D0  <<16)|( 0<<12)|( 3<<4)|(10<<0), //!<\n
      USB_OTG_HS_ULPI_D1_PB0 = (USB_OTG_HS_ULPI_D1  <<16)|( 1<<12)|( 0<<4)|(10<<0), //!<\n
      USB_OTG_HS_ULPI_D2_PB1 = (USB_OTG_HS_ULPI_D2  <<16)|( 1<<12)|( 1<<4)|(10<<0), //!<\n
      USB_OTG_HS_ULPI_D3_PB10 = (USB_OTG_HS_ULPI_D3  <<16)|( 1<<12)|(10<<4)|(10<<0), //!<\n
      USB_OTG_HS_ULPI_D4_PB11 = (USB_OTG_HS_ULPI_D4  <<16)|( 1<<12)|(11<<4)|(10<<0), //!<\n
      USB_OTG_HS_ULPI_D5_PB12 = (USB_OTG_HS_ULPI_D5  <<16)|( 1<<12)|(12<<4)|(10<<0), //!<\n
      USB_OTG_HS_ULPI_D6_PB13 = (USB_OTG_HS_ULPI_D6  <<16)|( 1<<12)|(13<<4)|(10<<0), //!<\n
      USB_OTG_HS_ULPI_D7_PB5 = (USB_OTG_HS_ULPI_D7  <<16)|( 1<<12)|( 5<<4)|(10<<0), //!<\n
      USB_OTG_HS_ULPI_DIR_PC2 = (USB_OTG_HS_ULPI_DIR <<16)|( 2<<12)|( 2<<4)|(10<<0), //!<\n
      USB_OTG_HS_ULPI_DIR_PI11 = (USB_OTG_HS_ULPI_DIR <<16)|( 8<<12)|(11<<4)|(10<<0), //!<\n
      USB_OTG_HS_ULPI_NXT_PC3 = (USB_OTG_HS_ULPI_NXT <<16)|( 2<<12)|( 3<<4)|(10<<0), //!<\n
      USB_OTG_HS_ULPI_NXT_PH4 = (USB_OTG_HS_ULPI_NXT <<16)|( 7<<12)|( 4<<4)|(10<<0), //!<\n
      USB_OTG_HS_ULPI_STP_PC0 = (USB_OTG_HS_ULPI_STP <<16)|( 2<<12)|( 0<<4)|(10<<0), //!<\n
      END_OF_TABLE = -1
    } MAP;

  public:
    //---------------------------------------------------------------
    /*! Set configuration of a GPIO
        \param gpio  Pointer to function register.
                     Use predefined constant \a 'GPIOx'
        \param pinId GPIO pin number (0,...15)
        \param mode  Selected pin mode.
                     Use constants defined in \b MODE, the constants
                     can be combined using bit-or operations.
        \param af    Number of selected alternate function. This
                     parameter is used only, when \b ALTERNATE_FUNC
                     is selected.
    */
    static void set( GPIO_TypeDef *gpio,
                     BYTE          pinId,
                     DWORD         mode,
                     BYTE          af = 0 );

    //---------------------------------------------------------------
    /*! Set GPIO to alternate function

        A GPIO can be connected to a onchip peripheral module. The
        enum \b 'Function' lists all peripheral signals which can be
        connected to a GPIO. This method uses a application specific
        mapping \b 'table'. The application has to define
        this \b 'table' on global scope. The entries of this table
        define on which port pin a peripheral signal is mapped.
        \param func  Selected peripheral signal as alternate function
        \param mode  Selected pin mode.
                     Use constants defined in \b MODE, the constants
                     can be combined using bit-or operations.
        \return
                - true, if \b func is included in \b table
                - false otherwise
    */
    static bool set( Function func,
                     DWORD    mode = 0 );

  public:
    //---------------------------------------------------------------
    /*! This table defines how an alternate function is mapped to the
        port pins. It must be defined by application software. The
        last entry of this table has to be \b 'END_OF_TABLE'.
    */
    static MAP table[];
    static Std::Report report;

}; //PinConfig

}  } //namespace
